-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- DO NOT EDIT THIS FILE
-- 
-- This file was generated from 'input/address_offset.vhd.template', version 1.1
-- by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline:
-- 
-- ./wuppercodegen/cli.py input/test-registers.yaml input/address_offset.vhd.template output/address_offset.vhd
-- 
-- Please do NOT edit this file, but edit the source file at 'input/address_offset.vhd.template'
-- 
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************



  --** Bar2

  --** GenericBoardInformation
    constant REG_BOARD_ID_SVN                   : std_logic_vector(19 downto 0) := x"00000";
    constant REG_BOARD_ID_TIMESTAMP             : std_logic_vector(19 downto 0) := x"00010";
    constant REG_STATUS_LEDS                    : std_logic_vector(19 downto 0) := x"00020";
    constant REG_GENERIC_CONSTANTS              : std_logic_vector(19 downto 0) := x"00030";
    constant REG_NUM_OF_CHANNELS                : std_logic_vector(19 downto 0) := x"00040";
    constant REG_CARD_TYPE                      : std_logic_vector(19 downto 0) := x"00050";
    constant REG_GBT_MAPPING                    : std_logic_vector(19 downto 0) := x"00060";

  --** CentralRouterControls

  --** CR_GBT_CTRL

  --** EGROUP_TH
    constant REG_CR_TH_GBT00_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01100";
    constant REG_CR_TH_GBT00_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01110";
    constant REG_CR_TH_GBT00_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01120";
    constant REG_CR_TH_GBT00_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01130";
    constant REG_CR_TH_GBT00_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01140";
    constant REG_CR_TH_GBT00_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01150";
    constant REG_CR_TH_GBT00_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01160";

  --** EGROUP_FH
    constant REG_CR_FH_GBT00_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01170";
    constant REG_CR_FH_GBT00_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01180";
    constant REG_CR_FH_GBT00_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01190";
    constant REG_CR_FH_GBT00_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"011a0";
    constant REG_CR_FH_GBT00_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"011b0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT01_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"011c0";
    constant REG_CR_TH_GBT01_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"011d0";
    constant REG_CR_TH_GBT01_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"011e0";
    constant REG_CR_TH_GBT01_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"011f0";
    constant REG_CR_TH_GBT01_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01200";
    constant REG_CR_TH_GBT01_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01210";
    constant REG_CR_TH_GBT01_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01220";

  --** EGROUP_FH
    constant REG_CR_FH_GBT01_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01230";
    constant REG_CR_FH_GBT01_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01240";
    constant REG_CR_FH_GBT01_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01250";
    constant REG_CR_FH_GBT01_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01260";
    constant REG_CR_FH_GBT01_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01270";

  --** EGROUP_TH
    constant REG_CR_TH_GBT02_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01280";
    constant REG_CR_TH_GBT02_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01290";
    constant REG_CR_TH_GBT02_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"012a0";
    constant REG_CR_TH_GBT02_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"012b0";
    constant REG_CR_TH_GBT02_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"012c0";
    constant REG_CR_TH_GBT02_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"012d0";
    constant REG_CR_TH_GBT02_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"012e0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT02_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"012f0";
    constant REG_CR_FH_GBT02_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01300";
    constant REG_CR_FH_GBT02_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01310";
    constant REG_CR_FH_GBT02_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01320";
    constant REG_CR_FH_GBT02_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01330";

  --** EGROUP_TH
    constant REG_CR_TH_GBT03_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01340";
    constant REG_CR_TH_GBT03_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01350";
    constant REG_CR_TH_GBT03_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01360";
    constant REG_CR_TH_GBT03_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01370";
    constant REG_CR_TH_GBT03_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01380";
    constant REG_CR_TH_GBT03_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01390";
    constant REG_CR_TH_GBT03_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"013a0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT03_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"013b0";
    constant REG_CR_FH_GBT03_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"013c0";
    constant REG_CR_FH_GBT03_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"013d0";
    constant REG_CR_FH_GBT03_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"013e0";
    constant REG_CR_FH_GBT03_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"013f0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT04_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01400";
    constant REG_CR_TH_GBT04_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01410";
    constant REG_CR_TH_GBT04_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01420";
    constant REG_CR_TH_GBT04_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01430";
    constant REG_CR_TH_GBT04_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01440";
    constant REG_CR_TH_GBT04_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01450";
    constant REG_CR_TH_GBT04_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01460";

  --** EGROUP_FH
    constant REG_CR_FH_GBT04_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01470";
    constant REG_CR_FH_GBT04_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01480";
    constant REG_CR_FH_GBT04_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01490";
    constant REG_CR_FH_GBT04_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"014a0";
    constant REG_CR_FH_GBT04_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"014b0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT05_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"014c0";
    constant REG_CR_TH_GBT05_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"014d0";
    constant REG_CR_TH_GBT05_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"014e0";
    constant REG_CR_TH_GBT05_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"014f0";
    constant REG_CR_TH_GBT05_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01500";
    constant REG_CR_TH_GBT05_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01510";
    constant REG_CR_TH_GBT05_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01520";

  --** EGROUP_FH
    constant REG_CR_FH_GBT05_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01530";
    constant REG_CR_FH_GBT05_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01540";
    constant REG_CR_FH_GBT05_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01550";
    constant REG_CR_FH_GBT05_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01560";
    constant REG_CR_FH_GBT05_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01570";

  --** EGROUP_TH
    constant REG_CR_TH_GBT06_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01580";
    constant REG_CR_TH_GBT06_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01590";
    constant REG_CR_TH_GBT06_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"015a0";
    constant REG_CR_TH_GBT06_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"015b0";
    constant REG_CR_TH_GBT06_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"015c0";
    constant REG_CR_TH_GBT06_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"015d0";
    constant REG_CR_TH_GBT06_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"015e0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT06_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"015f0";
    constant REG_CR_FH_GBT06_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01600";
    constant REG_CR_FH_GBT06_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01610";
    constant REG_CR_FH_GBT06_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01620";
    constant REG_CR_FH_GBT06_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01630";

  --** EGROUP_TH
    constant REG_CR_TH_GBT07_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01640";
    constant REG_CR_TH_GBT07_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01650";
    constant REG_CR_TH_GBT07_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01660";
    constant REG_CR_TH_GBT07_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01670";
    constant REG_CR_TH_GBT07_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01680";
    constant REG_CR_TH_GBT07_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01690";
    constant REG_CR_TH_GBT07_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"016a0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT07_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"016b0";
    constant REG_CR_FH_GBT07_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"016c0";
    constant REG_CR_FH_GBT07_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"016d0";
    constant REG_CR_FH_GBT07_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"016e0";
    constant REG_CR_FH_GBT07_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"016f0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT08_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01700";
    constant REG_CR_TH_GBT08_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01710";
    constant REG_CR_TH_GBT08_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01720";
    constant REG_CR_TH_GBT08_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01730";
    constant REG_CR_TH_GBT08_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01740";
    constant REG_CR_TH_GBT08_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01750";
    constant REG_CR_TH_GBT08_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01760";

  --** EGROUP_FH
    constant REG_CR_FH_GBT08_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01770";
    constant REG_CR_FH_GBT08_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01780";
    constant REG_CR_FH_GBT08_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01790";
    constant REG_CR_FH_GBT08_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"017a0";
    constant REG_CR_FH_GBT08_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"017b0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT09_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"017c0";
    constant REG_CR_TH_GBT09_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"017d0";
    constant REG_CR_TH_GBT09_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"017e0";
    constant REG_CR_TH_GBT09_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"017f0";
    constant REG_CR_TH_GBT09_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01800";
    constant REG_CR_TH_GBT09_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01810";
    constant REG_CR_TH_GBT09_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01820";

  --** EGROUP_FH
    constant REG_CR_FH_GBT09_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01830";
    constant REG_CR_FH_GBT09_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01840";
    constant REG_CR_FH_GBT09_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01850";
    constant REG_CR_FH_GBT09_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01860";
    constant REG_CR_FH_GBT09_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01870";

  --** EGROUP_TH
    constant REG_CR_TH_GBT10_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01880";
    constant REG_CR_TH_GBT10_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01890";
    constant REG_CR_TH_GBT10_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"018a0";
    constant REG_CR_TH_GBT10_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"018b0";
    constant REG_CR_TH_GBT10_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"018c0";
    constant REG_CR_TH_GBT10_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"018d0";
    constant REG_CR_TH_GBT10_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"018e0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT10_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"018f0";
    constant REG_CR_FH_GBT10_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01900";
    constant REG_CR_FH_GBT10_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01910";
    constant REG_CR_FH_GBT10_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01920";
    constant REG_CR_FH_GBT10_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01930";

  --** EGROUP_TH
    constant REG_CR_TH_GBT11_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01940";
    constant REG_CR_TH_GBT11_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01950";
    constant REG_CR_TH_GBT11_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01960";
    constant REG_CR_TH_GBT11_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01970";
    constant REG_CR_TH_GBT11_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01980";
    constant REG_CR_TH_GBT11_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01990";
    constant REG_CR_TH_GBT11_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"019a0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT11_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"019b0";
    constant REG_CR_FH_GBT11_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"019c0";
    constant REG_CR_FH_GBT11_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"019d0";
    constant REG_CR_FH_GBT11_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"019e0";
    constant REG_CR_FH_GBT11_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"019f0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT12_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01a00";
    constant REG_CR_TH_GBT12_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01a10";
    constant REG_CR_TH_GBT12_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01a20";
    constant REG_CR_TH_GBT12_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01a30";
    constant REG_CR_TH_GBT12_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01a40";
    constant REG_CR_TH_GBT12_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01a50";
    constant REG_CR_TH_GBT12_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01a60";

  --** EGROUP_FH
    constant REG_CR_FH_GBT12_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01a70";
    constant REG_CR_FH_GBT12_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01a80";
    constant REG_CR_FH_GBT12_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01a90";
    constant REG_CR_FH_GBT12_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01aa0";
    constant REG_CR_FH_GBT12_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01ab0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT13_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01ac0";
    constant REG_CR_TH_GBT13_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01ad0";
    constant REG_CR_TH_GBT13_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01ae0";
    constant REG_CR_TH_GBT13_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01af0";
    constant REG_CR_TH_GBT13_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01b00";
    constant REG_CR_TH_GBT13_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01b10";
    constant REG_CR_TH_GBT13_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01b20";

  --** EGROUP_FH
    constant REG_CR_FH_GBT13_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01b30";
    constant REG_CR_FH_GBT13_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01b40";
    constant REG_CR_FH_GBT13_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01b50";
    constant REG_CR_FH_GBT13_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01b60";
    constant REG_CR_FH_GBT13_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01b70";

  --** EGROUP_TH
    constant REG_CR_TH_GBT14_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01b80";
    constant REG_CR_TH_GBT14_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01b90";
    constant REG_CR_TH_GBT14_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01ba0";
    constant REG_CR_TH_GBT14_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01bb0";
    constant REG_CR_TH_GBT14_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01bc0";
    constant REG_CR_TH_GBT14_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01bd0";
    constant REG_CR_TH_GBT14_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01be0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT14_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01bf0";
    constant REG_CR_FH_GBT14_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01c00";
    constant REG_CR_FH_GBT14_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01c10";
    constant REG_CR_FH_GBT14_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01c20";
    constant REG_CR_FH_GBT14_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01c30";

  --** EGROUP_TH
    constant REG_CR_TH_GBT15_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01c40";
    constant REG_CR_TH_GBT15_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01c50";
    constant REG_CR_TH_GBT15_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01c60";
    constant REG_CR_TH_GBT15_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01c70";
    constant REG_CR_TH_GBT15_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01c80";
    constant REG_CR_TH_GBT15_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01c90";
    constant REG_CR_TH_GBT15_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01ca0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT15_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01cb0";
    constant REG_CR_FH_GBT15_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01cc0";
    constant REG_CR_FH_GBT15_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01cd0";
    constant REG_CR_FH_GBT15_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01ce0";
    constant REG_CR_FH_GBT15_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01cf0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT16_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01d00";
    constant REG_CR_TH_GBT16_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01d10";
    constant REG_CR_TH_GBT16_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01d20";
    constant REG_CR_TH_GBT16_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01d30";
    constant REG_CR_TH_GBT16_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01d40";
    constant REG_CR_TH_GBT16_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01d50";
    constant REG_CR_TH_GBT16_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01d60";

  --** EGROUP_FH
    constant REG_CR_FH_GBT16_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01d70";
    constant REG_CR_FH_GBT16_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01d80";
    constant REG_CR_FH_GBT16_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01d90";
    constant REG_CR_FH_GBT16_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01da0";
    constant REG_CR_FH_GBT16_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01db0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT17_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01dc0";
    constant REG_CR_TH_GBT17_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01dd0";
    constant REG_CR_TH_GBT17_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01de0";
    constant REG_CR_TH_GBT17_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01df0";
    constant REG_CR_TH_GBT17_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01e00";
    constant REG_CR_TH_GBT17_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01e10";
    constant REG_CR_TH_GBT17_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01e20";

  --** EGROUP_FH
    constant REG_CR_FH_GBT17_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01e30";
    constant REG_CR_FH_GBT17_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01e40";
    constant REG_CR_FH_GBT17_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01e50";
    constant REG_CR_FH_GBT17_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01e60";
    constant REG_CR_FH_GBT17_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01e70";

  --** EGROUP_TH
    constant REG_CR_TH_GBT18_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01e80";
    constant REG_CR_TH_GBT18_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01e90";
    constant REG_CR_TH_GBT18_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01ea0";
    constant REG_CR_TH_GBT18_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01eb0";
    constant REG_CR_TH_GBT18_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01ec0";
    constant REG_CR_TH_GBT18_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01ed0";
    constant REG_CR_TH_GBT18_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01ee0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT18_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01ef0";
    constant REG_CR_FH_GBT18_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01f00";
    constant REG_CR_FH_GBT18_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01f10";
    constant REG_CR_FH_GBT18_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01f20";
    constant REG_CR_FH_GBT18_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01f30";

  --** EGROUP_TH
    constant REG_CR_TH_GBT19_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01f40";
    constant REG_CR_TH_GBT19_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01f50";
    constant REG_CR_TH_GBT19_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01f60";
    constant REG_CR_TH_GBT19_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01f70";
    constant REG_CR_TH_GBT19_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01f80";
    constant REG_CR_TH_GBT19_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"01f90";
    constant REG_CR_TH_GBT19_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"01fa0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT19_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"01fb0";
    constant REG_CR_FH_GBT19_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"01fc0";
    constant REG_CR_FH_GBT19_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"01fd0";
    constant REG_CR_FH_GBT19_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"01fe0";
    constant REG_CR_FH_GBT19_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"01ff0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT20_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"02000";
    constant REG_CR_TH_GBT20_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02010";
    constant REG_CR_TH_GBT20_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"02020";
    constant REG_CR_TH_GBT20_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"02030";
    constant REG_CR_TH_GBT20_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"02040";
    constant REG_CR_TH_GBT20_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"02050";
    constant REG_CR_TH_GBT20_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"02060";

  --** EGROUP_FH
    constant REG_CR_FH_GBT20_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"02070";
    constant REG_CR_FH_GBT20_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02080";
    constant REG_CR_FH_GBT20_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"02090";
    constant REG_CR_FH_GBT20_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"020a0";
    constant REG_CR_FH_GBT20_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"020b0";

  --** EGROUP_TH
    constant REG_CR_TH_GBT21_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"020c0";
    constant REG_CR_TH_GBT21_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"020d0";
    constant REG_CR_TH_GBT21_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"020e0";
    constant REG_CR_TH_GBT21_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"020f0";
    constant REG_CR_TH_GBT21_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"02100";
    constant REG_CR_TH_GBT21_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"02110";
    constant REG_CR_TH_GBT21_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"02120";

  --** EGROUP_FH
    constant REG_CR_FH_GBT21_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"02130";
    constant REG_CR_FH_GBT21_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02140";
    constant REG_CR_FH_GBT21_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"02150";
    constant REG_CR_FH_GBT21_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"02160";
    constant REG_CR_FH_GBT21_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"02170";

  --** EGROUP_TH
    constant REG_CR_TH_GBT22_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"02180";
    constant REG_CR_TH_GBT22_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02190";
    constant REG_CR_TH_GBT22_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"021a0";
    constant REG_CR_TH_GBT22_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"021b0";
    constant REG_CR_TH_GBT22_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"021c0";
    constant REG_CR_TH_GBT22_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"021d0";
    constant REG_CR_TH_GBT22_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"021e0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT22_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"021f0";
    constant REG_CR_FH_GBT22_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02200";
    constant REG_CR_FH_GBT22_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"02210";
    constant REG_CR_FH_GBT22_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"02220";
    constant REG_CR_FH_GBT22_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"02230";

  --** EGROUP_TH
    constant REG_CR_TH_GBT23_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"02240";
    constant REG_CR_TH_GBT23_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"02250";
    constant REG_CR_TH_GBT23_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"02260";
    constant REG_CR_TH_GBT23_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"02270";
    constant REG_CR_TH_GBT23_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"02280";
    constant REG_CR_TH_GBT23_EGROUP5_CTRL       : std_logic_vector(19 downto 0) := x"02290";
    constant REG_CR_TH_GBT23_EGROUP6_CTRL       : std_logic_vector(19 downto 0) := x"022a0";

  --** EGROUP_FH
    constant REG_CR_FH_GBT23_EGROUP0_CTRL       : std_logic_vector(19 downto 0) := x"022b0";
    constant REG_CR_FH_GBT23_EGROUP1_CTRL       : std_logic_vector(19 downto 0) := x"022c0";
    constant REG_CR_FH_GBT23_EGROUP2_CTRL       : std_logic_vector(19 downto 0) := x"022d0";
    constant REG_CR_FH_GBT23_EGROUP3_CTRL       : std_logic_vector(19 downto 0) := x"022e0";
    constant REG_CR_FH_GBT23_EGROUP4_CTRL       : std_logic_vector(19 downto 0) := x"022f0";
    constant REG_CR_TH_UPDATE_CTRL              : std_logic_vector(19 downto 0) := x"02300";
    constant REG_CR_FH_UPDATE_CTRL              : std_logic_vector(19 downto 0) := x"02310";

  --** CentralRouterMonitors

  --** CR_GBT_MON
    constant REG_CR_TH_GBT00_MON                : std_logic_vector(19 downto 0) := x"03000";
    constant REG_CR_FH_GBT00_MON                : std_logic_vector(19 downto 0) := x"03010";
    constant REG_CR_TH_GBT01_MON                : std_logic_vector(19 downto 0) := x"03020";
    constant REG_CR_FH_GBT01_MON                : std_logic_vector(19 downto 0) := x"03030";
    constant REG_CR_TH_GBT02_MON                : std_logic_vector(19 downto 0) := x"03040";
    constant REG_CR_FH_GBT02_MON                : std_logic_vector(19 downto 0) := x"03050";
    constant REG_CR_TH_GBT03_MON                : std_logic_vector(19 downto 0) := x"03060";
    constant REG_CR_FH_GBT03_MON                : std_logic_vector(19 downto 0) := x"03070";
    constant REG_CR_TH_GBT04_MON                : std_logic_vector(19 downto 0) := x"03080";
    constant REG_CR_FH_GBT04_MON                : std_logic_vector(19 downto 0) := x"03090";
    constant REG_CR_TH_GBT05_MON                : std_logic_vector(19 downto 0) := x"030a0";
    constant REG_CR_FH_GBT05_MON                : std_logic_vector(19 downto 0) := x"030b0";
    constant REG_CR_TH_GBT06_MON                : std_logic_vector(19 downto 0) := x"030c0";
    constant REG_CR_FH_GBT06_MON                : std_logic_vector(19 downto 0) := x"030d0";
    constant REG_CR_TH_GBT07_MON                : std_logic_vector(19 downto 0) := x"030e0";
    constant REG_CR_FH_GBT07_MON                : std_logic_vector(19 downto 0) := x"030f0";
    constant REG_CR_TH_GBT08_MON                : std_logic_vector(19 downto 0) := x"03100";
    constant REG_CR_FH_GBT08_MON                : std_logic_vector(19 downto 0) := x"03110";
    constant REG_CR_TH_GBT09_MON                : std_logic_vector(19 downto 0) := x"03120";
    constant REG_CR_FH_GBT09_MON                : std_logic_vector(19 downto 0) := x"03130";
    constant REG_CR_TH_GBT10_MON                : std_logic_vector(19 downto 0) := x"03140";
    constant REG_CR_FH_GBT10_MON                : std_logic_vector(19 downto 0) := x"03150";
    constant REG_CR_TH_GBT11_MON                : std_logic_vector(19 downto 0) := x"03160";
    constant REG_CR_FH_GBT11_MON                : std_logic_vector(19 downto 0) := x"03170";
    constant REG_CR_TH_GBT12_MON                : std_logic_vector(19 downto 0) := x"03180";
    constant REG_CR_FH_GBT12_MON                : std_logic_vector(19 downto 0) := x"03190";
    constant REG_CR_TH_GBT13_MON                : std_logic_vector(19 downto 0) := x"031a0";
    constant REG_CR_FH_GBT13_MON                : std_logic_vector(19 downto 0) := x"031b0";
    constant REG_CR_TH_GBT14_MON                : std_logic_vector(19 downto 0) := x"031c0";
    constant REG_CR_FH_GBT14_MON                : std_logic_vector(19 downto 0) := x"031d0";
    constant REG_CR_TH_GBT15_MON                : std_logic_vector(19 downto 0) := x"031e0";
    constant REG_CR_FH_GBT15_MON                : std_logic_vector(19 downto 0) := x"031f0";
    constant REG_CR_TH_GBT16_MON                : std_logic_vector(19 downto 0) := x"03200";
    constant REG_CR_FH_GBT16_MON                : std_logic_vector(19 downto 0) := x"03210";
    constant REG_CR_TH_GBT17_MON                : std_logic_vector(19 downto 0) := x"03220";
    constant REG_CR_FH_GBT17_MON                : std_logic_vector(19 downto 0) := x"03230";
    constant REG_CR_TH_GBT18_MON                : std_logic_vector(19 downto 0) := x"03240";
    constant REG_CR_FH_GBT18_MON                : std_logic_vector(19 downto 0) := x"03250";
    constant REG_CR_TH_GBT19_MON                : std_logic_vector(19 downto 0) := x"03260";
    constant REG_CR_FH_GBT19_MON                : std_logic_vector(19 downto 0) := x"03270";
    constant REG_CR_TH_GBT20_MON                : std_logic_vector(19 downto 0) := x"03280";
    constant REG_CR_FH_GBT20_MON                : std_logic_vector(19 downto 0) := x"03290";
    constant REG_CR_TH_GBT21_MON                : std_logic_vector(19 downto 0) := x"032a0";
    constant REG_CR_FH_GBT21_MON                : std_logic_vector(19 downto 0) := x"032b0";
    constant REG_CR_TH_GBT22_MON                : std_logic_vector(19 downto 0) := x"032c0";
    constant REG_CR_FH_GBT22_MON                : std_logic_vector(19 downto 0) := x"032d0";
    constant REG_CR_TH_GBT23_MON                : std_logic_vector(19 downto 0) := x"032e0";
    constant REG_CR_FH_GBT23_MON                : std_logic_vector(19 downto 0) := x"032f0";

  --** GBTEmulatorControlsAndMonitors
    constant REG_GBT_EMU_ENA                    : std_logic_vector(19 downto 0) := x"04000";
    constant REG_GBT_EMU_CONFIG_WE_ARRAY        : std_logic_vector(19 downto 0) := x"04010";
    constant REG_GBT_EMU_CONFIG                 : std_logic_vector(19 downto 0) := x"04020";

  --** GBTWrapperControls
    constant REG_GBT_LOGIC_RESET                : std_logic_vector(19 downto 0) := x"05400";
    constant REG_GBT_GENERAL_CTRL               : std_logic_vector(19 downto 0) := x"05410";
    constant REG_GBT_MODE_CTRL                  : std_logic_vector(19 downto 0) := x"05420";
    constant REG_GBT_RXSLIDE                    : std_logic_vector(19 downto 0) := x"05480";
    constant REG_GBT_TXUSRRDY                   : std_logic_vector(19 downto 0) := x"05490";
    constant REG_GBT_RXUSRRDY                   : std_logic_vector(19 downto 0) := x"054a0";
    constant REG_GBT_GTTX_RESET                 : std_logic_vector(19 downto 0) := x"054b0";
    constant REG_GBT_GTRX_RESET                 : std_logic_vector(19 downto 0) := x"054c0";
    constant REG_GBT_PLL_RESET                  : std_logic_vector(19 downto 0) := x"054d0";
    constant REG_GBT_SOFT_TX_RESET              : std_logic_vector(19 downto 0) := x"054e0";
    constant REG_GBT_SOFT_RX_RESET              : std_logic_vector(19 downto 0) := x"054f0";
    constant REG_GBT_ODD_EVEN                   : std_logic_vector(19 downto 0) := x"05500";
    constant REG_GBT_TOPBOT                     : std_logic_vector(19 downto 0) := x"05510";
    constant REG_GBT_TX_TC_DLY_VALUE1           : std_logic_vector(19 downto 0) := x"05520";
    constant REG_GBT_TX_TC_DLY_VALUE2           : std_logic_vector(19 downto 0) := x"05530";
    constant REG_GBT_TX_OPT                     : std_logic_vector(19 downto 0) := x"05540";
    constant REG_GBT_RX_OPT                     : std_logic_vector(19 downto 0) := x"05550";
    constant REG_GBT_DATA_TXFORMAT              : std_logic_vector(19 downto 0) := x"05560";
    constant REG_GBT_DATA_RXFORMAT              : std_logic_vector(19 downto 0) := x"05570";
    constant REG_GBT_TX_RESET                   : std_logic_vector(19 downto 0) := x"05580";
    constant REG_GBT_RX_RESET                   : std_logic_vector(19 downto 0) := x"05590";
    constant REG_GBT_TX_TC_METHOD               : std_logic_vector(19 downto 0) := x"055a0";
    constant REG_GBT_OUTMUX_SEL                 : std_logic_vector(19 downto 0) := x"055b0";
    constant REG_GBT_DNLNK_FO_SEL               : std_logic_vector(19 downto 0) := x"05600";
    constant REG_GBT_UPLNK_FO_SEL               : std_logic_vector(19 downto 0) := x"05610";

  --** GBTWrapperMonitors
    constant REG_GBT_VERSION                    : std_logic_vector(19 downto 0) := x"06600";
    constant REG_GBT_TXRESET_DONE               : std_logic_vector(19 downto 0) := x"06680";
    constant REG_GBT_RXRESET_DONE               : std_logic_vector(19 downto 0) := x"06690";
    constant REG_GBT_TXFSMRESET_DONE            : std_logic_vector(19 downto 0) := x"066a0";
    constant REG_GBT_RXFSMRESET_DONE            : std_logic_vector(19 downto 0) := x"066b0";
    constant REG_GBT_CPLL_FBCLK_LOST            : std_logic_vector(19 downto 0) := x"066c0";
    constant REG_GBT_CPLL_LOCK                  : std_logic_vector(19 downto 0) := x"066d0";
    constant REG_GBT_RXCDR_LOCK                 : std_logic_vector(19 downto 0) := x"066e0";
    constant REG_GBT_CLK_SAMPLED                : std_logic_vector(19 downto 0) := x"066f0";
    constant REG_GBT_RX_IS_HEADER               : std_logic_vector(19 downto 0) := x"06700";
    constant REG_GBT_RX_IS_DATA                 : std_logic_vector(19 downto 0) := x"06710";
    constant REG_GBT_RX_HEADER_FOUND            : std_logic_vector(19 downto 0) := x"06720";
    constant REG_GBT_ALIGNMENT_DONE             : std_logic_vector(19 downto 0) := x"06730";
    constant REG_GBT_OUT_MUX_STATUS             : std_logic_vector(19 downto 0) := x"06740";
    constant REG_GBT_ERROR                      : std_logic_vector(19 downto 0) := x"06750";
    constant REG_GBT_GBT_TOPBOT_C               : std_logic_vector(19 downto 0) := x"06760";

  --** HouseKeepingControlsAndMonitors
    constant REG_HK_CTRL_CDCE                   : std_logic_vector(19 downto 0) := x"07200";
    constant REG_HK_CTRL                        : std_logic_vector(19 downto 0) := x"07210";
    constant REG_PLL_LOCK                       : std_logic_vector(19 downto 0) := x"07300";
    constant REG_HK_MON                         : std_logic_vector(19 downto 0) := x"07310";
    constant REG_SPI_WR                         : std_logic_vector(19 downto 0) := x"07400";
    constant REG_SPI_RD                         : std_logic_vector(19 downto 0) := x"07410";
    constant REG_I2C_WR                         : std_logic_vector(19 downto 0) := x"07420";
    constant REG_I2C_RD                         : std_logic_vector(19 downto 0) := x"07430";
    constant REG_DEBUG_PORT_CLK                 : std_logic_vector(19 downto 0) := x"07500";
    constant REG_DEBUG_PORT_GBT                 : std_logic_vector(19 downto 0) := x"07510";
    constant REG_INT_TEST_2                     : std_logic_vector(19 downto 0) := x"07800";
    constant REG_INT_TEST_3                     : std_logic_vector(19 downto 0) := x"07810";
