-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- DO NOT EDIT THIS FILE
-- 
-- This file was generated from 'input/control_record.vhd.template', version 1.1
-- by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline:
-- 
-- ./wuppercodegen/cli.py input/test-registers.yaml input/control_record.vhd.template output/control_record.vhd
-- 
-- Please do NOT edit this file, but edit the source file at 'input/control_record.vhd.template'
-- 
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************


  -- Bitfields of Control Record
  type register_map_gbt_emu_ena_type is record
    TOHOST                         : std_logic_vector(1 downto 1);    -- Enable GBT dummy emulator ToHost
    TOFRONTEND                     : std_logic_vector(0 downto 0);    -- Enable GBT dummy emulator ToFrontEnd
  end record;

  type register_map_gbt_emu_config_type is record
    WRADDR                         : std_logic_vector(45 downto 32);  -- write address bus
    WRDATA                         : std_logic_vector(15 downto 0);   -- write data bus
  end record;

  type register_map_gbt_mode_ctrl_type is record
    DESMUX_USE_SW                  : std_logic_vector(2 downto 2);    -- DESMUX_USE_SW
    RX_ALIGN_SW                    : std_logic_vector(1 downto 1);    -- RX_ALIGN_SW
    RX_ALIGN_TB_SW                 : std_logic_vector(0 downto 0);    -- RX_ALIGN_TB_SW
  end record;

  type register_map_gbt_rxslide_type is record
    BF1                            : std_logic_vector(59 downto 48);  -- RxSlide select [23:12]
    BF2                            : std_logic_vector(43 downto 32);  -- RxSlide select [11:0]
    BF3                            : std_logic_vector(27 downto 16);  -- RxSlide manual [23:12
    BF4                            : std_logic_vector(11 downto 0);   -- RxSlide manual [11:0]
  end record;

  type register_map_gbt_txusrrdy_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- TxUsrRdy [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- TxUsrRdy [11:0]
  end record;

  type register_map_gbt_rxusrrdy_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- RxUsrRdy [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- RxUsrRdy [11:0]
  end record;

  type register_map_gbt_gttx_reset_type is record
    BF1                            : std_logic_vector(30 downto 28);  -- SOFT_RESET [5:3]
    BF2                            : std_logic_vector(27 downto 16);  -- GTTX_RESET [23:12]
    BF3                            : std_logic_vector(14 downto 12);  -- SOFT_RESET [2:0]
    BF4                            : std_logic_vector(11 downto 0);   -- GTTX_RESET [11:0]
  end record;

  type register_map_gbt_gtrx_reset_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- GTRX_RESET [23:0]
    BF2                            : std_logic_vector(11 downto 0);   -- GTRX_RESET [11:0]
  end record;

  type register_map_gbt_pll_reset_type is record
    BF1                            : std_logic_vector(30 downto 28);  -- QPLL_RESET [5:3]
    BF2                            : std_logic_vector(27 downto 16);  -- CPLL_RESET [23:12]
    BF3                            : std_logic_vector(14 downto 12);  -- QPLL_RESET [2:0]
    BF4                            : std_logic_vector(11 downto 0);   -- CPLL_RESET [11:0]
  end record;

  type register_map_gbt_soft_tx_reset_type is record
    BF1                            : std_logic_vector(30 downto 28);  -- SOFT_TX_RESET_ALL [5:3]
    BF2                            : std_logic_vector(27 downto 16);  -- SOFT_TX_RESET_GT [23:12]
    BF3                            : std_logic_vector(14 downto 12);  -- SOFT_TX_RESET_ALL [2:0]
    BF4                            : std_logic_vector(11 downto 0);   -- SOFT_TX_RESET_GT [11:0]
  end record;

  type register_map_gbt_soft_rx_reset_type is record
    BF1                            : std_logic_vector(30 downto 28);  -- SOFT_RX_RESET_ALL [5:3]
    BF2                            : std_logic_vector(27 downto 16);  -- SOFT_RX_RESET_GT [23:12]
    BF3                            : std_logic_vector(14 downto 12);  -- SOFT_RX_RESET_ALL [2:0]
    BF4                            : std_logic_vector(11 downto 0);   -- SOFT_RX_RESET_GT [11:0]
  end record;

  type register_map_gbt_odd_even_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- OddEven [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- OddEven [11:0]
  end record;

  type register_map_gbt_topbot_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- TopBot [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- TopBot [11:0]
  end record;

  type register_map_gbt_data_txformat_type is record
    BF1                            : std_logic_vector(55 downto 32);  -- DATA_TXFORMAT [47:24]
    BF2                            : std_logic_vector(23 downto 0);   -- DATA_TXFORMAT [23:0]
  end record;

  type register_map_gbt_data_rxformat_type is record
    BF1                            : std_logic_vector(55 downto 32);  -- DATA_RXFORMAT [47:24]
    BF2                            : std_logic_vector(23 downto 0);   -- DATA_RXFORMAT [23:0]
  end record;

  type register_map_gbt_tx_reset_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- TX Logic reset [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- TX Logic reset [11:0]
  end record;

  type register_map_gbt_rx_reset_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- RX Logic reset [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- RX Logic reset [11:0]
  end record;

  type register_map_gbt_tx_tc_method_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- TX time domain crossing method [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- TX time domain crossing method [11:0]
  end record;

  type register_map_gbt_outmux_sel_type is record
    BF1                            : std_logic_vector(27 downto 16);  -- Descrambler output MUX selection [23:12]
    BF2                            : std_logic_vector(11 downto 0);   -- Descrambler output MUX selection [11:0]
  end record;

  type register_map_hk_ctrl_cdce_type is record
    REF_SEL                        : std_logic_vector(2 downto 2);    -- REF_SEL
    PD                             : std_logic_vector(1 downto 1);    -- PD
    SYNC                           : std_logic_vector(0 downto 0);    -- SYNC
  end record;

  type register_map_hk_ctrl_type is record
    I2C_CONFIG_TRIG                : std_logic_vector(1 downto 1);    -- i2c_config_trig
    I2C_CLKFREQ_SEL                : std_logic_vector(0 downto 0);    -- i2c_clkfreq_sel
  end record;

  type register_map_spi_wr_type is record
    SPI_DIN                        : std_logic_vector(31 downto 0);   -- SPI WRITE Data
    SPI_WREN                       : std_logic_vector(64 downto 64);  -- Any write to this register triggers an SPI Write
  end record;

  type register_map_spi_rd_type is record
    SPI_RDEN                       : std_logic_vector(64 downto 64);  -- Any write to this register pops the last SPI data from the FIFO
  end record;

  type register_map_i2c_wr_type is record
    BF2                            : std_logic_vector(24 downto 24);  -- Write two bytes
    BF3                            : std_logic_vector(23 downto 16);  -- Data byte 2
    BF4                            : std_logic_vector(15 downto 8);   -- Data byte 1
    BF5                            : std_logic_vector(7 downto 1);    -- Slave address
    BF6                            : std_logic_vector(0 downto 0);    -- READ/<o>WRITE</o>
    I2C_WREN                       : std_logic_vector(64 downto 64);  -- Any write to this register triggers an I2C read or write sequence
  end record;

  type register_map_i2c_rd_type is record
    I2C_RDEN                       : std_logic_vector(64 downto 64);  -- Any write to this register pops the last I2C data from the FIFO
  end record;


  -- Control Record
  type register_map_control_type is record
    STATUS_LEDS                    : std_logic_vector(7 downto 0);    -- Board GPIO Leds
    CR_TH_GBT00_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT00_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT00_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT00_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT00_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT00_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT00_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT01_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT01_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT01_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT01_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT01_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT01_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT01_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT02_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT02_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT02_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT02_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT02_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT02_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT02_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT03_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT03_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT03_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT03_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT03_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT03_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT03_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT04_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT04_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT04_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT04_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT04_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT04_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT04_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT05_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT05_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT05_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT05_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT05_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT05_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT05_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT06_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT06_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT06_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT06_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT06_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT06_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT06_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT07_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT07_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT07_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT07_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT07_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT07_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT07_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT08_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT08_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT08_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT08_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT08_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT08_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT08_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT09_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT09_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT09_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT09_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT09_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT09_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT09_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT10_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT10_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT10_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT10_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT10_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT10_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT10_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT11_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT11_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT11_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT11_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT11_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT11_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT11_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT12_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT12_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT12_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT12_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT12_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT12_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT12_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT13_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT13_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT13_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT13_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT13_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT13_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT13_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT14_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT14_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT14_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT14_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT14_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT14_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT14_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT15_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT15_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT15_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT15_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT15_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT15_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT15_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT16_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT16_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT16_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT16_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT16_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT16_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT16_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT17_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT17_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT17_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT17_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT17_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT17_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT17_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT18_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT18_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT18_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT18_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT18_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT18_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT18_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT19_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT19_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT19_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT19_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT19_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT19_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT19_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT20_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT20_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT20_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT20_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT20_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT20_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT20_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT21_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT21_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT21_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT21_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT21_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT21_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT21_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT22_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT22_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT22_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT22_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT22_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT22_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT22_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_GBT23_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP5_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_TH_GBT23_EGROUP6_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
    CR_FH_GBT23_EGROUP0_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT23_EGROUP1_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT23_EGROUP2_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT23_EGROUP3_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_FH_GBT23_EGROUP4_CTRL       : std_logic_vector(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
    CR_TH_UPDATE_CTRL              : std_logic_vector(64 downto 64);  -- See Central Router Doc
    CR_FH_UPDATE_CTRL              : std_logic_vector(64 downto 64);  -- See Central Router Doc
    GBT_EMU_ENA                    : register_map_gbt_emu_ena_type;
    GBT_EMU_CONFIG_WE_ARRAY        : std_logic_vector(6 downto 0);    -- write enable array, every bit is one emulator RAM block
    GBT_EMU_CONFIG                 : register_map_gbt_emu_config_type;
    GBT_LOGIC_RESET                : std_logic_vector(63 downto 0);   -- Not internally connected (?)
    GBT_GENERAL_CTRL               : std_logic_vector(0 downto 0);    -- Alignment chk reset (not self clearing)
    GBT_MODE_CTRL                  : register_map_gbt_mode_ctrl_type;
    GBT_RXSLIDE                    : register_map_gbt_rxslide_type;
    GBT_TXUSRRDY                   : register_map_gbt_txusrrdy_type;
    GBT_RXUSRRDY                   : register_map_gbt_rxusrrdy_type;
    GBT_GTTX_RESET                 : register_map_gbt_gttx_reset_type;
    GBT_GTRX_RESET                 : register_map_gbt_gtrx_reset_type;
    GBT_PLL_RESET                  : register_map_gbt_pll_reset_type;
    GBT_SOFT_TX_RESET              : register_map_gbt_soft_tx_reset_type;
    GBT_SOFT_RX_RESET              : register_map_gbt_soft_rx_reset_type;
    GBT_ODD_EVEN                   : register_map_gbt_odd_even_type;
    GBT_TOPBOT                     : register_map_gbt_topbot_type; 
    GBT_TX_TC_DLY_VALUE1           : std_logic_vector(47 downto 0);   -- TX_TC_DLY_VALUE [47:0]
    GBT_TX_TC_DLY_VALUE2           : std_logic_vector(47 downto 0);   -- TX_TC_DLY_VALUE [95:48]
    GBT_TX_OPT                     : std_logic_vector(47 downto 0);   -- TX_OPT
    GBT_RX_OPT                     : std_logic_vector(47 downto 0);   -- RX_OPT
    GBT_DATA_TXFORMAT              : register_map_gbt_data_txformat_type;
    GBT_DATA_RXFORMAT              : register_map_gbt_data_rxformat_type;
    GBT_TX_RESET                   : register_map_gbt_tx_reset_type;
    GBT_RX_RESET                   : register_map_gbt_rx_reset_type;
    GBT_TX_TC_METHOD               : register_map_gbt_tx_tc_method_type;
    GBT_OUTMUX_SEL                 : register_map_gbt_outmux_sel_type;
    GBT_DNLNK_FO_SEL               : std_logic_vector(31 downto 0);   -- ToHost FanOut/Selector. Every bitfield is a channel:
                                                                      --   1 : GBT_EMU, select GBT Emulator for a specific CentralRouter channel
                                                                      --   0 : GBT_WRAP, select real GBT link for a specific CentralRouter channel
                                                                      
    GBT_UPLNK_FO_SEL               : std_logic_vector(31 downto 0);   -- ToFrontEnd FanOut/Selector. Every bitfield is a channel:
                                                                      --   1 : GBT_EMU, select GBT Emulator for a specific GBT link
                                                                      --   0 : TTC_DEC, select CentralRouter data (including TTC) for a specific GBT link
                                                                      
    HK_CTRL_CDCE                   : register_map_hk_ctrl_cdce_type;
    HK_CTRL                        : register_map_hk_ctrl_type;    
    SPI_WR                         : register_map_spi_wr_type;     
    SPI_RD                         : register_map_spi_rd_type;     
    I2C_WR                         : register_map_i2c_wr_type;     
    I2C_RD                         : register_map_i2c_rd_type;     
    DEBUG_PORT_CLK                 : std_logic_vector(3 downto 0);    -- Debug clock and L1A port on SMA HTGx#4
    DEBUG_PORT_GBT                 : std_logic_vector(6 downto 0);    -- Debug GBT data bit N (119..0) on SMA HTGx#3
    INT_TEST_2                     : std_logic_vector(64 downto 64);  -- Fire a test MSIx interrupt #2
    INT_TEST_3                     : std_logic_vector(64 downto 64);  -- Fire a test MSIx interrupt #3
  end record;