-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- DO NOT EDIT THIS FILE
-- 
-- This file was generated from 'input/read.vhd.template', version 1.1
-- by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline:
-- 
-- ./wuppercodegen/cli.py input/test-registers.yaml input/read.vhd.template output/read.vhd
-- 
-- Please do NOT edit this file, but edit the source file at 'input/read.vhd.template'
-- 
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************


--
-- Control Registers
--
  when REG_STATUS_LEDS                    => register_read_data_40_s(7 downto 0)     <= register_map_control_s.STATUS_LEDS;                   -- Board GPIO Leds
  when REG_CR_TH_GBT00_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT00_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT00_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT00_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT00_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT00_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT00_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT01_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT01_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT01_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT01_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT01_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT01_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT02_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT02_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT02_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT02_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT02_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT02_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT03_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT03_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT03_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT03_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT03_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT03_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT04_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT04_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT04_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT04_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT04_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT04_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT05_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT05_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT05_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT05_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT05_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT05_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT06_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT06_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT06_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT06_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT06_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT06_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT07_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT07_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT07_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT07_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT07_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT07_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT08_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT08_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT08_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT08_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT08_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT08_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT09_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT09_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT09_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT09_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT09_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT09_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT10_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT10_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT10_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT10_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT10_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT10_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT11_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT11_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT11_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT11_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT11_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT11_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT12_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT12_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT12_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT12_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT12_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT12_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT13_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT13_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT13_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT13_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT13_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT13_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT14_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT14_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT14_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT14_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT14_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT14_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT15_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT15_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT15_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT15_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT15_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT15_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT16_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT16_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT16_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT16_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT16_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT16_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT17_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT17_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT17_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT17_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT17_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT17_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT18_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT18_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT18_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT18_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT18_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT18_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT19_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT19_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT19_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT19_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT19_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT19_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT20_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT20_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT20_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT20_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT20_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT20_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT21_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT21_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT21_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT21_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT21_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT21_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT22_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT22_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT22_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT22_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT22_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT22_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP0_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP1_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP2_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP3_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP4_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP5_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP5_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP6_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_TH_GBT23_EGROUP6_CTRL;      -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP0_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT23_EGROUP0_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP1_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT23_EGROUP1_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP2_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT23_EGROUP2_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP3_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT23_EGROUP3_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP4_CTRL       => register_read_data_40_s(63 downto 0)    <= register_map_control_s.CR_FH_GBT23_EGROUP4_CTRL;      -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_GBT_EMU_ENA                    => register_read_data_40_s(1 downto 1)     <= register_map_control_s.GBT_EMU_ENA.TOHOST;            -- Enable GBT dummy emulator ToHost
                                             register_read_data_40_s(0 downto 0)     <= register_map_control_s.GBT_EMU_ENA.TOFRONTEND;        -- Enable GBT dummy emulator ToFrontEnd
  when REG_GBT_EMU_CONFIG_WE_ARRAY        => register_read_data_40_s(6 downto 0)     <= register_map_control_s.GBT_EMU_CONFIG_WE_ARRAY;       -- write enable array, every bit is one emulator RAM block
  when REG_GBT_EMU_CONFIG                 => register_read_data_40_s(45 downto 32)   <= register_map_control_s.GBT_EMU_CONFIG.WRADDR;         -- write address bus
                                             register_read_data_40_s(15 downto 0)    <= register_map_control_s.GBT_EMU_CONFIG.WRDATA;         -- write data bus
  when REG_GBT_LOGIC_RESET                => register_read_data_40_s(63 downto 0)    <= register_map_control_s.GBT_LOGIC_RESET;               -- Not internally connected (?)
  when REG_GBT_GENERAL_CTRL               => register_read_data_40_s(0 downto 0)     <= register_map_control_s.GBT_GENERAL_CTRL;              -- Alignment chk reset (not self clearing)
  when REG_GBT_MODE_CTRL                  => register_read_data_40_s(2 downto 2)     <= register_map_control_s.GBT_MODE_CTRL.DESMUX_USE_SW;   -- DESMUX_USE_SW
                                             register_read_data_40_s(1 downto 1)     <= register_map_control_s.GBT_MODE_CTRL.RX_ALIGN_SW;     -- RX_ALIGN_SW
                                             register_read_data_40_s(0 downto 0)     <= register_map_control_s.GBT_MODE_CTRL.RX_ALIGN_TB_SW;  -- RX_ALIGN_TB_SW
  when REG_GBT_RXSLIDE                    => register_read_data_40_s(59 downto 48)   <= register_map_control_s.GBT_RXSLIDE.BF1;               -- RxSlide select [23:12]
                                             register_read_data_40_s(43 downto 32)   <= register_map_control_s.GBT_RXSLIDE.BF2;               -- RxSlide select [11:0]
                                             register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_RXSLIDE.BF3;               -- RxSlide manual [23:12
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_RXSLIDE.BF4;               -- RxSlide manual [11:0]
  when REG_GBT_TXUSRRDY                   => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_TXUSRRDY.BF1;              -- TxUsrRdy [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_TXUSRRDY.BF2;              -- TxUsrRdy [11:0]
  when REG_GBT_RXUSRRDY                   => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_RXUSRRDY.BF1;              -- RxUsrRdy [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_RXUSRRDY.BF2;              -- RxUsrRdy [11:0]
  when REG_GBT_GTTX_RESET                 => register_read_data_40_s(30 downto 28)   <= register_map_control_s.GBT_GTTX_RESET.BF1;            -- SOFT_RESET [5:3]
                                             register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_GTTX_RESET.BF2;            -- GTTX_RESET [23:12]
                                             register_read_data_40_s(14 downto 12)   <= register_map_control_s.GBT_GTTX_RESET.BF3;            -- SOFT_RESET [2:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_GTTX_RESET.BF4;            -- GTTX_RESET [11:0]
  when REG_GBT_GTRX_RESET                 => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_GTRX_RESET.BF1;            -- GTRX_RESET [23:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_GTRX_RESET.BF2;            -- GTRX_RESET [11:0]
  when REG_GBT_PLL_RESET                  => register_read_data_40_s(30 downto 28)   <= register_map_control_s.GBT_PLL_RESET.BF1;             -- QPLL_RESET [5:3]
                                             register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_PLL_RESET.BF2;             -- CPLL_RESET [23:12]
                                             register_read_data_40_s(14 downto 12)   <= register_map_control_s.GBT_PLL_RESET.BF3;             -- QPLL_RESET [2:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_PLL_RESET.BF4;             -- CPLL_RESET [11:0]
  when REG_GBT_SOFT_TX_RESET              => register_read_data_40_s(30 downto 28)   <= register_map_control_s.GBT_SOFT_TX_RESET.BF1;         -- SOFT_TX_RESET_ALL [5:3]
                                             register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_SOFT_TX_RESET.BF2;         -- SOFT_TX_RESET_GT [23:12]
                                             register_read_data_40_s(14 downto 12)   <= register_map_control_s.GBT_SOFT_TX_RESET.BF3;         -- SOFT_TX_RESET_ALL [2:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_SOFT_TX_RESET.BF4;         -- SOFT_TX_RESET_GT [11:0]
  when REG_GBT_SOFT_RX_RESET              => register_read_data_40_s(30 downto 28)   <= register_map_control_s.GBT_SOFT_RX_RESET.BF1;         -- SOFT_RX_RESET_ALL [5:3]
                                             register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_SOFT_RX_RESET.BF2;         -- SOFT_RX_RESET_GT [23:12]
                                             register_read_data_40_s(14 downto 12)   <= register_map_control_s.GBT_SOFT_RX_RESET.BF3;         -- SOFT_RX_RESET_ALL [2:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_SOFT_RX_RESET.BF4;         -- SOFT_RX_RESET_GT [11:0]
  when REG_GBT_ODD_EVEN                   => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_ODD_EVEN.BF1;              -- OddEven [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_ODD_EVEN.BF2;              -- OddEven [11:0]
  when REG_GBT_TOPBOT                     => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_TOPBOT.BF1;                -- TopBot [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_TOPBOT.BF2;                -- TopBot [11:0]
  when REG_GBT_TX_TC_DLY_VALUE1           => register_read_data_40_s(47 downto 0)    <= register_map_control_s.GBT_TX_TC_DLY_VALUE1;          -- TX_TC_DLY_VALUE [47:0]
  when REG_GBT_TX_TC_DLY_VALUE2           => register_read_data_40_s(47 downto 0)    <= register_map_control_s.GBT_TX_TC_DLY_VALUE2;          -- TX_TC_DLY_VALUE [95:48]
  when REG_GBT_TX_OPT                     => register_read_data_40_s(47 downto 0)    <= register_map_control_s.GBT_TX_OPT;                    -- TX_OPT
  when REG_GBT_RX_OPT                     => register_read_data_40_s(47 downto 0)    <= register_map_control_s.GBT_RX_OPT;                    -- RX_OPT
  when REG_GBT_DATA_TXFORMAT              => register_read_data_40_s(55 downto 32)   <= register_map_control_s.GBT_DATA_TXFORMAT.BF1;         -- DATA_TXFORMAT [47:24]
                                             register_read_data_40_s(23 downto 0)    <= register_map_control_s.GBT_DATA_TXFORMAT.BF2;         -- DATA_TXFORMAT [23:0]
  when REG_GBT_DATA_RXFORMAT              => register_read_data_40_s(55 downto 32)   <= register_map_control_s.GBT_DATA_RXFORMAT.BF1;         -- DATA_RXFORMAT [47:24]
                                             register_read_data_40_s(23 downto 0)    <= register_map_control_s.GBT_DATA_RXFORMAT.BF2;         -- DATA_RXFORMAT [23:0]
  when REG_GBT_TX_RESET                   => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_TX_RESET.BF1;              -- TX Logic reset [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_TX_RESET.BF2;              -- TX Logic reset [11:0]
  when REG_GBT_RX_RESET                   => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_RX_RESET.BF1;              -- RX Logic reset [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_RX_RESET.BF2;              -- RX Logic reset [11:0]
  when REG_GBT_TX_TC_METHOD               => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_TX_TC_METHOD.BF1;          -- TX time domain crossing method [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_TX_TC_METHOD.BF2;          -- TX time domain crossing method [11:0]
  when REG_GBT_OUTMUX_SEL                 => register_read_data_40_s(27 downto 16)   <= register_map_control_s.GBT_OUTMUX_SEL.BF1;            -- Descrambler output MUX selection [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_control_s.GBT_OUTMUX_SEL.BF2;            -- Descrambler output MUX selection [11:0]
  when REG_GBT_DNLNK_FO_SEL               => register_read_data_40_s(31 downto 0)    <= register_map_control_s.GBT_DNLNK_FO_SEL;              -- ToHost FanOut/Selector. Every bitfield is a channel:
                                                                                                                                              --   1 : GBT_EMU, select GBT Emulator for a specific CentralRouter channel
                                                                                                                                              --   0 : GBT_WRAP, select real GBT link for a specific CentralRouter channel
                                                                                                                                              
  when REG_GBT_UPLNK_FO_SEL               => register_read_data_40_s(31 downto 0)    <= register_map_control_s.GBT_UPLNK_FO_SEL;              -- ToFrontEnd FanOut/Selector. Every bitfield is a channel:
                                                                                                                                              --   1 : GBT_EMU, select GBT Emulator for a specific GBT link
                                                                                                                                              --   0 : TTC_DEC, select CentralRouter data (including TTC) for a specific GBT link
                                                                                                                                              
  when REG_HK_CTRL_CDCE                   => register_read_data_40_s(2 downto 2)     <= register_map_control_s.HK_CTRL_CDCE.REF_SEL;          -- REF_SEL
                                             register_read_data_40_s(1 downto 1)     <= register_map_control_s.HK_CTRL_CDCE.PD;               -- PD
                                             register_read_data_40_s(0 downto 0)     <= register_map_control_s.HK_CTRL_CDCE.SYNC;             -- SYNC
  when REG_HK_CTRL                        => register_read_data_40_s(1 downto 1)     <= register_map_control_s.HK_CTRL.I2C_CONFIG_TRIG;       -- i2c_config_trig
                                             register_read_data_40_s(0 downto 0)     <= register_map_control_s.HK_CTRL.I2C_CLKFREQ_SEL;       -- i2c_clkfreq_sel
  when REG_SPI_WR                         => register_read_data_40_s(31 downto 0)    <= register_map_control_s.SPI_WR.SPI_DIN;                -- SPI WRITE Data
  when REG_I2C_WR                         => register_read_data_40_s(24 downto 24)   <= register_map_control_s.I2C_WR.BF2;                    -- Write two bytes
                                             register_read_data_40_s(23 downto 16)   <= register_map_control_s.I2C_WR.BF3;                    -- Data byte 2
                                             register_read_data_40_s(15 downto 8)    <= register_map_control_s.I2C_WR.BF4;                    -- Data byte 1
                                             register_read_data_40_s(7 downto 1)     <= register_map_control_s.I2C_WR.BF5;                    -- Slave address
                                             register_read_data_40_s(0 downto 0)     <= register_map_control_s.I2C_WR.BF6;                    -- READ/<o>WRITE</o>
  when REG_DEBUG_PORT_CLK                 => register_read_data_40_s(3 downto 0)     <= register_map_control_s.DEBUG_PORT_CLK;                -- Debug clock and L1A port on SMA HTGx#4
  when REG_DEBUG_PORT_GBT                 => register_read_data_40_s(6 downto 0)     <= register_map_control_s.DEBUG_PORT_GBT;                -- Debug GBT data bit N (119..0) on SMA HTGx#3

--
-- Monitor registers
--

-- General Board Info
  when REG_BOARD_ID_SVN                   => register_read_data_40_s(15 downto 0)    <= register_map_monitor_s.register_map_gen_board_info.BOARD_ID_SVN;                  -- Board ID SVN Revision
  when REG_BOARD_ID_TIMESTAMP             => register_read_data_40_s(39 downto 0)    <= register_map_monitor_s.register_map_gen_board_info.BOARD_ID_TIMESTAMP;            -- Board ID Date / Time in BCD format YYMMDDhhmm
  when REG_GENERIC_CONSTANTS              => register_read_data_40_s(15 downto 8)    <= register_map_monitor_s.register_map_gen_board_info.GENERIC_CONSTANTS.INTERRUPTS;  -- Number of Interrupts
                                             register_read_data_40_s(7 downto 0)     <= register_map_monitor_s.register_map_gen_board_info.GENERIC_CONSTANTS.DESCRIPTORS; -- Number of Descriptors
  when REG_NUM_OF_CHANNELS                => register_read_data_40_s(7 downto 0)     <= register_map_monitor_s.register_map_gen_board_info.NUM_OF_CHANNELS;               -- Number of GBT Channels
  when REG_CARD_TYPE                      => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_gen_board_info.CARD_TYPE;                     -- Card Type:
                                                                                                                                              --   - 709: VC709
                                                                                                                                              --   - 710: HTG710
                                                                                                                                              
  when REG_GBT_MAPPING                    => register_read_data_40_s(7 downto 0)     <= register_map_monitor_s.register_map_gen_board_info.GBT_MAPPING;                   -- CXP-to-GBT mapping:
                                                                                                                                              --   0: NORMAL CXP1 1-12 CXP2 13-24
                                                                                                                                              --   1: ALTERNATE CXP1 1-4,9-12,17-20
                                                                                                                                              

-- Housekeeping and global monitor
  when REG_PLL_LOCK                       => register_read_data_40_s(0 downto 0)     <= register_map_monitor_s.register_map_hk_monitor.PLL_LOCK;                      -- Main MMCM PLL Lock Status
  when REG_HK_MON                         => register_read_data_40_s(1 downto 1)     <= register_map_monitor_s.register_map_hk_monitor.HK_MON.CDCE_PLL_LOCK;          -- CDCE_PLL_LOCK
                                             register_read_data_40_s(0 downto 0)     <= register_map_monitor_s.register_map_hk_monitor.HK_MON.I2C_ACK_ERROR;          -- i2c_ack_error
  when REG_SPI_WR                         => register_read_data_40_s(32 downto 32)   <= register_map_monitor_s.register_map_hk_monitor.SPI_WR.SPI_FULL;               -- SPI FIFO Full
  when REG_SPI_RD                         => register_read_data_40_s(32 downto 32)   <= register_map_monitor_s.register_map_hk_monitor.SPI_RD.SPI_EMPTY;              -- SPI FIFO Empty
                                             register_read_data_40_s(31 downto 0)    <= register_map_monitor_s.register_map_hk_monitor.SPI_RD.SPI_DOUT;               -- SPI READ Data
  when REG_I2C_WR                         => register_read_data_40_s(25 downto 25)   <= register_map_monitor_s.register_map_hk_monitor.I2C_WR.I2C_FULL;               -- I2C FIFO full
  when REG_I2C_RD                         => register_read_data_40_s(8 downto 8)     <= register_map_monitor_s.register_map_hk_monitor.I2C_RD.I2C_EMPTY;              -- I2C FIFO Empty
                                             register_read_data_40_s(7 downto 0)     <= register_map_monitor_s.register_map_hk_monitor.I2C_RD.I2C_DOUT;               -- I2C READ Data

-- GBT monitor
  when REG_GBT_VERSION                    => register_read_data_40_s(63 downto 48)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.DATA;              -- Data
                                             register_read_data_40_s(47 downto 32)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.GBT_VERSION;       -- GBT Version
                                             register_read_data_40_s(31 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.GTH_IP_VERSION;    -- GTH IP Version
                                             register_read_data_40_s(15 downto 3)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.RESERVED;          -- Reserved
                                             register_read_data_40_s(2 downto 2)     <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.GTHREFCLK_SEL;     -- GTHREFCLK SEL
                                             register_read_data_40_s(1 downto 1)     <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.RX_CLK_SEL;        -- RX CLK SEL
                                             register_read_data_40_s(0 downto 0)     <= register_map_monitor_s.register_map_gbt_monitor.GBT_VERSION.PLL_SEL;           -- PLL SEL
  when REG_GBT_TXRESET_DONE               => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_TXRESET_DONE.BF1;          -- TX Reset done [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_TXRESET_DONE.BF2;          -- TX Reset done [11:0]
  when REG_GBT_RXRESET_DONE               => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXRESET_DONE.BF1;          -- RX Reset done [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXRESET_DONE.BF2;          -- RX Reset done [11:0]
  when REG_GBT_TXFSMRESET_DONE            => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_TXFSMRESET_DONE.BF1;       -- TX FSM Reset done [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_TXFSMRESET_DONE.BF2;       -- TX FSM Reset done [11:0]
  when REG_GBT_RXFSMRESET_DONE            => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXFSMRESET_DONE.BF1;       -- RX FSM Reset done [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXFSMRESET_DONE.BF2;       -- RX FSM Reset done [11:0]
  when REG_GBT_CPLL_FBCLK_LOST            => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_FBCLK_LOST.BF1;       -- CPLL FBCLK LOST [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_FBCLK_LOST.BF2;       -- CPLL FBCLK LOST [11:0]
  when REG_GBT_CPLL_LOCK                  => register_read_data_40_s(30 downto 28)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_LOCK.BF1;             -- QPLL LOCK [5:3]
                                             register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_LOCK.BF2;             -- CPLL LOCK [23:12]
                                             register_read_data_40_s(14 downto 12)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_LOCK.BF3;             -- QPLL LOCK [2:0]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_CPLL_LOCK.BF4;             -- CPLL LOCK [11:0]
  when REG_GBT_RXCDR_LOCK                 => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXCDR_LOCK.BF1;            -- RX CDR LOCK [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RXCDR_LOCK.BF2;            -- RX CDR LOCK [11:0]
  when REG_GBT_CLK_SAMPLED                => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_CLK_SAMPLED.BF1;           -- clk sampled [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_CLK_SAMPLED.BF2;           -- clk sampled [11:0]
  when REG_GBT_RX_IS_HEADER               => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_IS_HEADER.BF1;          -- RX IS HEADER [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_IS_HEADER.BF2;          -- RX IS HEADER [11:0]
  when REG_GBT_RX_IS_DATA                 => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_IS_DATA.BF1;            -- RX IS DATA [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_IS_DATA.BF2;            -- RX IS DATA [11:0]
  when REG_GBT_RX_HEADER_FOUND            => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_HEADER_FOUND.BF1;       -- RX HEADER FOUND [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_RX_HEADER_FOUND.BF2;       -- RX HEADER FOUND [11:0]
  when REG_GBT_ALIGNMENT_DONE             => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_ALIGNMENT_DONE.BF1;        -- RX ALIGNMENT DONE [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_ALIGNMENT_DONE.BF2;        -- RX ALIGNMENT DONE [11:0]
  when REG_GBT_OUT_MUX_STATUS             => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_OUT_MUX_STATUS.BF1;        -- GBT output mux status [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_OUT_MUX_STATUS.BF2;        -- GBT output mux status [11:0]
  when REG_GBT_ERROR                      => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_ERROR.BF1;                 -- Error flags [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_ERROR.BF2;                 -- Error flags [11:0]
  when REG_GBT_GBT_TOPBOT_C               => register_read_data_40_s(27 downto 16)   <= register_map_monitor_s.register_map_gbt_monitor.GBT_GBT_TOPBOT_C.BF1;          -- TopBot_c [23:12]
                                             register_read_data_40_s(11 downto 0)    <= register_map_monitor_s.register_map_gbt_monitor.GBT_GBT_TOPBOT_C.BF2;          -- TopBot_c [11:0]

-- CentralRouter monitor
  when REG_CR_TH_GBT00_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT00_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT00_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT00_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT01_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT01_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT01_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT01_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT02_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT02_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT02_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT02_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT03_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT03_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT03_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT03_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT04_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT04_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT04_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT04_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT05_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT05_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT05_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT05_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT06_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT06_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT06_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT06_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT07_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT07_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT07_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT07_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT08_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT08_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT08_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT08_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT09_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT09_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT09_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT09_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT10_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT10_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT10_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT10_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT11_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT11_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT11_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT11_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT12_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT12_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT12_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT12_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT13_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT13_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT13_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT13_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT14_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT14_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT14_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT14_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT15_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT15_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT15_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT15_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT16_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT16_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT16_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT16_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT17_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT17_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT17_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT17_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT18_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT18_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT18_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT18_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT19_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT19_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT19_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT19_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT20_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT20_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT20_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT20_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT21_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT21_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT21_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT21_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT22_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT22_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT22_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT22_MON;               -- See Central Router Doc
  when REG_CR_TH_GBT23_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_TH_GBT23_MON;               -- See Central Router Doc
  when REG_CR_FH_GBT23_MON                => register_read_data_40_s(63 downto 0)    <= register_map_monitor_s.register_map_cr_monitor.CR_FH_GBT23_MON;               -- See Central Router Doc
