/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */
/* DO NOT EDIT THIS FILE */
/*  */
/* This file was generated from 'input/registers.c.template', version 1.1 */
/* by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline: */
/*  */
/* ./wuppercodegen/cli.py input/test-registers.yaml input/registers.c.template output/registers.c */
/*  */
/* Please do NOT edit this file, but edit the source file at 'input/registers.c.template' */
/*  */
/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */
/* *************************************************************************** */


flx_register_t flx_registers[] =
  {
    // Bar2
    // GenericBoardInformation
    { "BOARD_ID_SVN",
      "Board ID SVN Revision",
      0x00000,
      0x000000000000FFFF,
      0
      FLX_REG_READ
    },
    { "BOARD_ID_TIMESTAMP",
      "Board ID Date / Time in BCD format YYMMDDhhmm",
      0x00010,
      0x000000FFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "STATUS_LEDS",
      "Board GPIO Leds",
      0x00020,
      0x00000000000000FF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GENERIC_CONSTANTS_INTERRUPTS",
      "Number of Interrupts",
      0x00030,
      0x000000000000FF00,
      8
      FLX_REG_READ
    },
    { "GENERIC_CONSTANTS_DESCRIPTORS",
      "Number of Descriptors",
      0x00030,
      0x00000000000000FF,
      0
      FLX_REG_READ
    },
    { "NUM_OF_CHANNELS",
      "Number of GBT Channels",
      0x00040,
      0x00000000000000FF,
      0
      FLX_REG_READ
    },
    { "CARD_TYPE",
      "Card Type:\n  - 709: VC709\n  - 710: HTG710\n",
      0x00050,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "GBT_MAPPING",
      "CXP-to-GBT mapping:\n  0: NORMAL CXP1 1-12 CXP2 13-24\n  1: ALTERNATE CXP1 1-4,9-12,17-20\n",
      0x00060,
      0x00000000000000FF,
      0
      FLX_REG_READ
    },
    // CentralRouterControls
    // CR_GBT_CTRL
    // EGROUP_TH
    { "CR_TH_GBT00_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01100,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01110,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01120,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01130,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01140,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01150,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT00_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01160,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT00_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01170,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT00_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01180,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT00_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01190,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT00_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x011A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT00_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x011B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT01_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x011C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x011D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x011E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x011F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01200,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01210,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT01_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01220,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT01_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01230,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT01_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01240,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT01_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01250,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT01_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01260,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT01_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01270,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT02_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01280,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01290,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x012A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x012B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x012C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x012D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT02_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x012E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT02_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x012F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT02_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01300,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT02_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01310,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT02_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01320,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT02_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01330,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT03_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01340,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01350,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01360,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01370,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01380,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01390,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT03_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x013A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT03_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x013B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT03_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x013C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT03_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x013D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT03_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x013E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT03_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x013F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT04_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01400,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01410,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01420,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01430,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01440,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01450,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT04_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01460,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT04_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01470,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT04_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01480,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT04_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01490,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT04_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x014A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT04_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x014B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT05_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x014C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x014D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x014E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x014F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01500,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01510,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT05_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01520,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT05_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01530,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT05_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01540,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT05_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01550,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT05_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01560,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT05_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01570,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT06_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01580,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01590,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x015A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x015B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x015C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x015D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT06_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x015E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT06_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x015F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT06_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01600,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT06_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01610,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT06_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01620,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT06_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01630,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT07_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01640,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01650,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01660,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01670,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01680,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01690,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT07_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x016A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT07_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x016B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT07_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x016C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT07_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x016D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT07_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x016E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT07_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x016F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT08_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01700,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01710,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01720,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01730,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01740,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01750,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT08_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01760,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT08_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01770,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT08_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01780,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT08_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01790,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT08_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x017A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT08_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x017B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT09_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x017C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x017D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x017E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x017F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01800,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01810,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT09_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01820,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT09_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01830,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT09_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01840,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT09_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01850,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT09_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01860,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT09_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01870,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT10_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01880,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01890,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x018A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x018B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x018C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x018D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT10_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x018E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT10_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x018F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT10_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01900,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT10_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01910,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT10_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01920,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT10_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01930,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT11_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01940,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01950,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01960,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01970,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01980,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01990,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT11_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x019A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT11_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x019B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT11_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x019C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT11_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x019D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT11_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x019E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT11_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x019F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT12_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT12_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01A60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT12_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01A70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT12_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01A80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT12_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01A90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT12_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01AA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT12_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01AB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT13_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01AC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01AD0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01AE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01AF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01B00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01B10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT13_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01B20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT13_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01B30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT13_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01B40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT13_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01B50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT13_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01B60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT13_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01B70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT14_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01B80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01B90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01BA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01BB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01BC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01BD0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT14_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01BE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT14_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01BF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT14_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01C00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT14_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01C10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT14_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01C20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT14_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01C30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT15_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01C90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT15_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01CA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT15_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01CB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT15_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01CC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT15_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01CD0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT15_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01CE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT15_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01CF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT16_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT16_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01D60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT16_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01D70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT16_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01D80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT16_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01D90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT16_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01DA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT16_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01DB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT17_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01DC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01DD0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01DE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01DF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01E00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01E10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT17_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01E20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT17_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01E30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT17_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01E40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT17_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01E50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT17_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01E60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT17_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01E70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT18_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01E80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01E90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01EA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01EB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01EC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01ED0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT18_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01EE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT18_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01EF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT18_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01F00,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT18_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01F10,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT18_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01F20,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT18_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01F30,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT19_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F40,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F50,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F60,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F70,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F80,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01F90,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT19_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x01FA0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT19_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01FB0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT19_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01FC0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT19_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01FD0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT19_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01FE0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT19_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x01FF0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT20_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02000,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02010,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02020,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02030,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02040,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02050,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT20_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02060,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT20_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02070,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT20_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02080,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT20_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02090,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT20_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x020A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT20_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x020B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT21_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x020C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x020D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x020E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x020F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02100,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02110,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT21_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02120,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT21_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02130,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT21_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02140,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT21_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02150,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT21_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02160,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT21_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02170,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT22_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02180,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02190,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x021A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x021B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x021C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x021D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT22_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x021E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT22_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x021F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT22_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02200,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT22_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02210,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT22_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02220,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT22_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x02230,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_TH
    { "CR_TH_GBT23_EGROUP0_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02240,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP1_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02250,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP2_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02260,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP3_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02270,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP4_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02280,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP5_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x02290,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_GBT23_EGROUP6_CTRL",
      "See Central Router Doc, indices [5,6] are optimized out in wideMode",
      0x022A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // EGROUP_FH
    { "CR_FH_GBT23_EGROUP0_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x022B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT23_EGROUP1_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x022C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT23_EGROUP2_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x022D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT23_EGROUP3_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x022E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_FH_GBT23_EGROUP4_CTRL",
      "See Central Router Doc, indices [3,4] are optimized out in wideMode",
      0x022F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "CR_TH_UPDATE_CTRL",
      "See Central Router Doc",
      0x02300,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "CR_FH_UPDATE_CTRL",
      "See Central Router Doc",
      0x02310,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    // CentralRouterMonitors
    // CR_GBT_MON
    { "CR_TH_GBT00_MON",
      "See Central Router Doc",
      0x03000,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT00_MON",
      "See Central Router Doc",
      0x03010,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT01_MON",
      "See Central Router Doc",
      0x03020,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT01_MON",
      "See Central Router Doc",
      0x03030,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT02_MON",
      "See Central Router Doc",
      0x03040,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT02_MON",
      "See Central Router Doc",
      0x03050,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT03_MON",
      "See Central Router Doc",
      0x03060,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT03_MON",
      "See Central Router Doc",
      0x03070,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT04_MON",
      "See Central Router Doc",
      0x03080,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT04_MON",
      "See Central Router Doc",
      0x03090,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT05_MON",
      "See Central Router Doc",
      0x030A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT05_MON",
      "See Central Router Doc",
      0x030B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT06_MON",
      "See Central Router Doc",
      0x030C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT06_MON",
      "See Central Router Doc",
      0x030D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT07_MON",
      "See Central Router Doc",
      0x030E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT07_MON",
      "See Central Router Doc",
      0x030F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT08_MON",
      "See Central Router Doc",
      0x03100,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT08_MON",
      "See Central Router Doc",
      0x03110,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT09_MON",
      "See Central Router Doc",
      0x03120,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT09_MON",
      "See Central Router Doc",
      0x03130,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT10_MON",
      "See Central Router Doc",
      0x03140,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT10_MON",
      "See Central Router Doc",
      0x03150,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT11_MON",
      "See Central Router Doc",
      0x03160,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT11_MON",
      "See Central Router Doc",
      0x03170,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT12_MON",
      "See Central Router Doc",
      0x03180,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT12_MON",
      "See Central Router Doc",
      0x03190,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT13_MON",
      "See Central Router Doc",
      0x031A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT13_MON",
      "See Central Router Doc",
      0x031B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT14_MON",
      "See Central Router Doc",
      0x031C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT14_MON",
      "See Central Router Doc",
      0x031D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT15_MON",
      "See Central Router Doc",
      0x031E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT15_MON",
      "See Central Router Doc",
      0x031F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT16_MON",
      "See Central Router Doc",
      0x03200,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT16_MON",
      "See Central Router Doc",
      0x03210,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT17_MON",
      "See Central Router Doc",
      0x03220,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT17_MON",
      "See Central Router Doc",
      0x03230,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT18_MON",
      "See Central Router Doc",
      0x03240,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT18_MON",
      "See Central Router Doc",
      0x03250,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT19_MON",
      "See Central Router Doc",
      0x03260,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT19_MON",
      "See Central Router Doc",
      0x03270,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT20_MON",
      "See Central Router Doc",
      0x03280,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT20_MON",
      "See Central Router Doc",
      0x03290,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT21_MON",
      "See Central Router Doc",
      0x032A0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT21_MON",
      "See Central Router Doc",
      0x032B0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT22_MON",
      "See Central Router Doc",
      0x032C0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT22_MON",
      "See Central Router Doc",
      0x032D0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_TH_GBT23_MON",
      "See Central Router Doc",
      0x032E0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    { "CR_FH_GBT23_MON",
      "See Central Router Doc",
      0x032F0,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ
    },
    // GBTEmulatorControlsAndMonitors
    { "GBT_EMU_ENA_TOHOST",
      "Enable GBT dummy emulator ToHost",
      0x04000,
      0x0000000000000002,
      1
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_EMU_ENA_TOFRONTEND",
      "Enable GBT dummy emulator ToFrontEnd",
      0x04000,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_EMU_CONFIG_WE_ARRAY",
      "write enable array, every bit is one emulator RAM block",
      0x04010,
      0x000000000000007F,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_EMU_CONFIG_WRADDR",
      "write address bus",
      0x04020,
      0x00003FFF00000000,
      32
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_EMU_CONFIG_WRDATA",
      "write data bus",
      0x04020,
      0x000000000000FFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // GBTWrapperControls
    { "GBT_LOGIC_RESET",
      "Not internally connected (?)",
      0x05400,
      0xFFFFFFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GENERAL_CTRL",
      "Alignment chk reset (not self clearing)",
      0x05410,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_MODE_CTRL_DESMUX_USE_SW",
      "DESMUX_USE_SW",
      0x05420,
      0x0000000000000004,
      2
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_MODE_CTRL_RX_ALIGN_SW",
      "RX_ALIGN_SW",
      0x05420,
      0x0000000000000002,
      1
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_MODE_CTRL_RX_ALIGN_TB_SW",
      "RX_ALIGN_TB_SW",
      0x05420,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXSLIDE_BF1",
      "RxSlide select [23:12]",
      0x05480,
      0x0FFF000000000000,
      48
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXSLIDE_BF2",
      "RxSlide select [11:0]",
      0x05480,
      0x00000FFF00000000,
      32
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXSLIDE_BF3",
      "RxSlide manual [23:12",
      0x05480,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXSLIDE_BF4",
      "RxSlide manual [11:0]",
      0x05480,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TXUSRRDY_BF1",
      "TxUsrRdy [23:12]",
      0x05490,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TXUSRRDY_BF2",
      "TxUsrRdy [11:0]",
      0x05490,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXUSRRDY_BF1",
      "RxUsrRdy [23:12]",
      0x054A0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RXUSRRDY_BF2",
      "RxUsrRdy [11:0]",
      0x054A0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTTX_RESET_BF1",
      "SOFT_RESET [5:3]",
      0x054B0,
      0x0000000070000000,
      28
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTTX_RESET_BF2",
      "GTTX_RESET [23:12]",
      0x054B0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTTX_RESET_BF3",
      "SOFT_RESET [2:0]",
      0x054B0,
      0x0000000000007000,
      12
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTTX_RESET_BF4",
      "GTTX_RESET [11:0]",
      0x054B0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTRX_RESET_BF1",
      "GTRX_RESET [23:0]",
      0x054C0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_GTRX_RESET_BF2",
      "GTRX_RESET [11:0]",
      0x054C0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_PLL_RESET_BF1",
      "QPLL_RESET [5:3]",
      0x054D0,
      0x0000000070000000,
      28
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_PLL_RESET_BF2",
      "CPLL_RESET [23:12]",
      0x054D0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_PLL_RESET_BF3",
      "QPLL_RESET [2:0]",
      0x054D0,
      0x0000000000007000,
      12
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_PLL_RESET_BF4",
      "CPLL_RESET [11:0]",
      0x054D0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_TX_RESET_BF1",
      "SOFT_TX_RESET_ALL [5:3]",
      0x054E0,
      0x0000000070000000,
      28
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_TX_RESET_BF2",
      "SOFT_TX_RESET_GT [23:12]",
      0x054E0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_TX_RESET_BF3",
      "SOFT_TX_RESET_ALL [2:0]",
      0x054E0,
      0x0000000000007000,
      12
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_TX_RESET_BF4",
      "SOFT_TX_RESET_GT [11:0]",
      0x054E0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_RX_RESET_BF1",
      "SOFT_RX_RESET_ALL [5:3]",
      0x054F0,
      0x0000000070000000,
      28
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_RX_RESET_BF2",
      "SOFT_RX_RESET_GT [23:12]",
      0x054F0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_RX_RESET_BF3",
      "SOFT_RX_RESET_ALL [2:0]",
      0x054F0,
      0x0000000000007000,
      12
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_SOFT_RX_RESET_BF4",
      "SOFT_RX_RESET_GT [11:0]",
      0x054F0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_ODD_EVEN_BF1",
      "OddEven [23:12]",
      0x05500,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_ODD_EVEN_BF2",
      "OddEven [11:0]",
      0x05500,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TOPBOT_BF1",
      "TopBot [23:12]",
      0x05510,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TOPBOT_BF2",
      "TopBot [11:0]",
      0x05510,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_TC_DLY_VALUE1",
      "TX_TC_DLY_VALUE [47:0]",
      0x05520,
      0x0000FFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_TC_DLY_VALUE2",
      "TX_TC_DLY_VALUE [95:48]",
      0x05530,
      0x0000FFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_OPT",
      "TX_OPT",
      0x05540,
      0x0000FFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RX_OPT",
      "RX_OPT",
      0x05550,
      0x0000FFFFFFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_DATA_TXFORMAT_BF1",
      "DATA_TXFORMAT [47:24]",
      0x05560,
      0x00FFFFFF00000000,
      32
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_DATA_TXFORMAT_BF2",
      "DATA_TXFORMAT [23:0]",
      0x05560,
      0x0000000000FFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_DATA_RXFORMAT_BF1",
      "DATA_RXFORMAT [47:24]",
      0x05570,
      0x00FFFFFF00000000,
      32
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_DATA_RXFORMAT_BF2",
      "DATA_RXFORMAT [23:0]",
      0x05570,
      0x0000000000FFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_RESET_BF1",
      "TX Logic reset [23:12]",
      0x05580,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_RESET_BF2",
      "TX Logic reset [11:0]",
      0x05580,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RX_RESET_BF1",
      "RX Logic reset [23:12]",
      0x05590,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_RX_RESET_BF2",
      "RX Logic reset [11:0]",
      0x05590,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_TC_METHOD_BF1",
      "TX time domain crossing method [23:12]",
      0x055A0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_TX_TC_METHOD_BF2",
      "TX time domain crossing method [11:0]",
      0x055A0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_OUTMUX_SEL_BF1",
      "Descrambler output MUX selection [23:12]",
      0x055B0,
      0x000000000FFF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_OUTMUX_SEL_BF2",
      "Descrambler output MUX selection [11:0]",
      0x055B0,
      0x0000000000000FFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_DNLNK_FO_SEL",
      "ToHost FanOut/Selector. Every bitfield is a channel:\n  1 : GBT_EMU, select GBT Emulator for a specific CentralRouter channel\n  0 : GBT_WRAP, select real GBT link for a specific CentralRouter channel\n",
      0x05600,
      0x00000000FFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "GBT_UPLNK_FO_SEL",
      "ToFrontEnd FanOut/Selector. Every bitfield is a channel:\n  1 : GBT_EMU, select GBT Emulator for a specific GBT link\n  0 : TTC_DEC, select CentralRouter data (including TTC) for a specific GBT link\n",
      0x05610,
      0x00000000FFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    // GBTWrapperMonitors
    { "GBT_VERSION_DATA",
      "Data",
      0x06600,
      0xFFFF000000000000,
      48
      FLX_REG_READ
    },
    { "GBT_VERSION_GBT_VERSION",
      "GBT Version",
      0x06600,
      0x0000FFFF00000000,
      32
      FLX_REG_READ
    },
    { "GBT_VERSION_GTH_IP_VERSION",
      "GTH IP Version",
      0x06600,
      0x00000000FFFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_VERSION_RESERVED",
      "Reserved",
      0x06600,
      0x000000000000FFF8,
      3
      FLX_REG_READ
    },
    { "GBT_VERSION_GTHREFCLK_SEL",
      "GTHREFCLK SEL",
      0x06600,
      0x0000000000000004,
      2
      FLX_REG_READ
    },
    { "GBT_VERSION_RX_CLK_SEL",
      "RX CLK SEL",
      0x06600,
      0x0000000000000002,
      1
      FLX_REG_READ
    },
    { "GBT_VERSION_PLL_SEL",
      "PLL SEL",
      0x06600,
      0x0000000000000001,
      0
      FLX_REG_READ
    },
    { "GBT_TXRESET_DONE_BF1",
      "TX Reset done [23:12]",
      0x06680,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_TXRESET_DONE_BF2",
      "TX Reset done [11:0]",
      0x06680,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RXRESET_DONE_BF1",
      "RX Reset done [23:12]",
      0x06690,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RXRESET_DONE_BF2",
      "RX Reset done [11:0]",
      0x06690,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_TXFSMRESET_DONE_BF1",
      "TX FSM Reset done [23:12]",
      0x066A0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_TXFSMRESET_DONE_BF2",
      "TX FSM Reset done [11:0]",
      0x066A0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RXFSMRESET_DONE_BF1",
      "RX FSM Reset done [23:12]",
      0x066B0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RXFSMRESET_DONE_BF2",
      "RX FSM Reset done [11:0]",
      0x066B0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_CPLL_FBCLK_LOST_BF1",
      "CPLL FBCLK LOST [23:12]",
      0x066C0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_CPLL_FBCLK_LOST_BF2",
      "CPLL FBCLK LOST [11:0]",
      0x066C0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_CPLL_LOCK_BF1",
      "QPLL LOCK [5:3]",
      0x066D0,
      0x0000000070000000,
      28
      FLX_REG_READ
    },
    { "GBT_CPLL_LOCK_BF2",
      "CPLL LOCK [23:12]",
      0x066D0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_CPLL_LOCK_BF3",
      "QPLL LOCK [2:0]",
      0x066D0,
      0x0000000000007000,
      12
      FLX_REG_READ
    },
    { "GBT_CPLL_LOCK_BF4",
      "CPLL LOCK [11:0]",
      0x066D0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RXCDR_LOCK_BF1",
      "RX CDR LOCK [23:12]",
      0x066E0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RXCDR_LOCK_BF2",
      "RX CDR LOCK [11:0]",
      0x066E0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_CLK_SAMPLED_BF1",
      "clk sampled [23:12]",
      0x066F0,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_CLK_SAMPLED_BF2",
      "clk sampled [11:0]",
      0x066F0,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RX_IS_HEADER_BF1",
      "RX IS HEADER [23:12]",
      0x06700,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RX_IS_HEADER_BF2",
      "RX IS HEADER [11:0]",
      0x06700,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RX_IS_DATA_BF1",
      "RX IS DATA [23:12]",
      0x06710,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RX_IS_DATA_BF2",
      "RX IS DATA [11:0]",
      0x06710,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_RX_HEADER_FOUND_BF1",
      "RX HEADER FOUND [23:12]",
      0x06720,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_RX_HEADER_FOUND_BF2",
      "RX HEADER FOUND [11:0]",
      0x06720,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_ALIGNMENT_DONE_BF1",
      "RX ALIGNMENT DONE [23:12]",
      0x06730,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_ALIGNMENT_DONE_BF2",
      "RX ALIGNMENT DONE [11:0]",
      0x06730,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_OUT_MUX_STATUS_BF1",
      "GBT output mux status [23:12]",
      0x06740,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_OUT_MUX_STATUS_BF2",
      "GBT output mux status [11:0]",
      0x06740,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_ERROR_BF1",
      "Error flags [23:12]",
      0x06750,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_ERROR_BF2",
      "Error flags [11:0]",
      0x06750,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    { "GBT_GBT_TOPBOT_C_BF1",
      "TopBot_c [23:12]",
      0x06760,
      0x000000000FFF0000,
      16
      FLX_REG_READ
    },
    { "GBT_GBT_TOPBOT_C_BF2",
      "TopBot_c [11:0]",
      0x06760,
      0x0000000000000FFF,
      0
      FLX_REG_READ
    },
    // HouseKeepingControlsAndMonitors
    { "HK_CTRL_CDCE_REF_SEL",
      "REF_SEL",
      0x07200,
      0x0000000000000004,
      2
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "HK_CTRL_CDCE_PD",
      "PD",
      0x07200,
      0x0000000000000002,
      1
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "HK_CTRL_CDCE_SYNC",
      "SYNC",
      0x07200,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "HK_CTRL_I2C_CONFIG_TRIG",
      "i2c_config_trig",
      0x07210,
      0x0000000000000002,
      1
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "HK_CTRL_I2C_CLKFREQ_SEL",
      "i2c_clkfreq_sel",
      0x07210,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "PLL_LOCK",
      "Main MMCM PLL Lock Status",
      0x07300,
      0x0000000000000001,
      0
      FLX_REG_READ
    },
    { "HK_MON_CDCE_PLL_LOCK",
      "CDCE_PLL_LOCK",
      0x07310,
      0x0000000000000002,
      1
      FLX_REG_READ
    },
    { "HK_MON_I2C_ACK_ERROR",
      "i2c_ack_error",
      0x07310,
      0x0000000000000001,
      0
      FLX_REG_READ
    },
    { "SPI_WR_SPI_FULL",
      "SPI FIFO Full",
      0x07400,
      0x0000000100000000,
      32
      FLX_REG_READ
    },
    { "SPI_WR_SPI_DIN",
      "SPI WRITE Data",
      0x07400,
      0x00000000FFFFFFFF,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "SPI_WR_SPI_WREN",
      "Any write to this register triggers an SPI Write",
      0x07400,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "SPI_RD_SPI_EMPTY",
      "SPI FIFO Empty",
      0x07410,
      0x0000000100000000,
      32
      FLX_REG_READ
    },
    { "SPI_RD_SPI_DOUT",
      "SPI READ Data",
      0x07410,
      0x00000000FFFFFFFF,
      0
      FLX_REG_READ
    },
    { "SPI_RD_SPI_RDEN",
      "Any write to this register pops the last SPI data from the FIFO",
      0x07410,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "I2C_WR_I2C_FULL",
      "I2C FIFO full",
      0x07420,
      0x0000000002000000,
      25
      FLX_REG_READ
    },
    { "I2C_WR_BF2",
      "Write two bytes",
      0x07420,
      0x0000000001000000,
      24
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "I2C_WR_BF3",
      "Data byte 2",
      0x07420,
      0x0000000000FF0000,
      16
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "I2C_WR_BF4",
      "Data byte 1",
      0x07420,
      0x000000000000FF00,
      8
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "I2C_WR_BF5",
      "Slave address",
      0x07420,
      0x00000000000000FE,
      1
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "I2C_WR_BF6",
      "READ/<o>WRITE</o>",
      0x07420,
      0x0000000000000001,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "I2C_WR_I2C_WREN",
      "Any write to this register triggers an I2C read or write sequence",
      0x07420,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "I2C_RD_I2C_EMPTY",
      "I2C FIFO Empty",
      0x07430,
      0x0000000000000100,
      8
      FLX_REG_READ
    },
    { "I2C_RD_I2C_DOUT",
      "I2C READ Data",
      0x07430,
      0x00000000000000FF,
      0
      FLX_REG_READ
    },
    { "I2C_RD_I2C_RDEN",
      "Any write to this register pops the last I2C data from the FIFO",
      0x07430,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "DEBUG_PORT_CLK",
      "Debug clock and L1A port on SMA HTGx#4",
      0x07500,
      0x000000000000000F,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "DEBUG_PORT_GBT",
      "Debug GBT data bit N (119..0) on SMA HTGx#3",
      0x07510,
      0x000000000000007F,
      0
      FLX_REG_READ|FLX_REG_WRITE
    },
    { "INT_TEST_2",
      "Fire a test MSIx interrupt #2",
      0x07800,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { "INT_TEST_3",
      "Fire a test MSIx interrupt #3",
      0x07810,
      0x0000000000000000,
      0
      FLX_REG_READ
    },
    { NULL,
      NULL,
      0,
      0,
      0,
      0
    }
  };