-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- DO NOT EDIT THIS FILE
-- 
-- This file was generated from 'input/trigger.vhd.template', version 1.1
-- by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline:
-- 
-- ./wuppercodegen/cli.py input/test-registers.yaml input/trigger.vhd.template output/trigger.vhd
-- 
-- Please do NOT edit this file, but edit the source file at 'input/trigger.vhd.template'
-- 
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************


  register_map_control_s.CR_TH_UPDATE_CTRL              <= REG_CR_TH_UPDATE_CTRL_C;           -- See Central Router Doc
  register_map_control_s.CR_FH_UPDATE_CTRL              <= REG_CR_FH_UPDATE_CTRL_C;           -- See Central Router Doc
  register_map_control_s.SPI_WR                         <= REG_SPI_WR_SPI_WREN_C;             -- Any write to this register triggers an SPI Write
  register_map_control_s.SPI_RD                         <= REG_SPI_RD_SPI_RDEN_C;             -- Any write to this register pops the last SPI data from the FIFO
  register_map_control_s.I2C_WR                         <= REG_I2C_WR_I2C_WREN_C;             -- Any write to this register triggers an I2C read or write sequence
  register_map_control_s.I2C_RD                         <= REG_I2C_RD_I2C_RDEN_C;             -- Any write to this register pops the last I2C data from the FIFO
  register_map_control_s.INT_TEST_2                     <= REG_INT_TEST_2_C;                  -- Fire a test MSIx interrupt #2
  register_map_control_s.INT_TEST_3                     <= REG_INT_TEST_3_C;                  -- Fire a test MSIx interrupt #3
