-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- DO NOT EDIT THIS FILE
-- 
-- This file was generated from 'input/write.vhd.template', version 1.1
-- by the script 'wuppercodegen', version: xx.yy.zz, using the following commandline:
-- 
-- ./wuppercodegen/cli.py input/test-registers.yaml input/write.vhd.template output/write.vhd
-- 
-- Please do NOT edit this file, but edit the source file at 'input/write.vhd.template'
-- 
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************
-- ***************************************************************************


  when REG_STATUS_LEDS                    => register_map_control_s.STATUS_LEDS                    <= register_write_data_40_s(7 downto 0);    -- Board GPIO Leds
  when REG_CR_TH_GBT00_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT00_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT00_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT00_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT00_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT00_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT00_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT00_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT00_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT01_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT01_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT01_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT01_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT01_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT01_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT01_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT01_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT02_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT02_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT02_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT02_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT02_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT02_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT02_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT02_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT03_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT03_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT03_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT03_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT03_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT03_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT03_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT03_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT04_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT04_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT04_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT04_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT04_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT04_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT04_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT04_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT05_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT05_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT05_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT05_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT05_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT05_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT05_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT05_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT06_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT06_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT06_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT06_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT06_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT06_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT06_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT06_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT07_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT07_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT07_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT07_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT07_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT07_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT07_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT07_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT08_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT08_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT08_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT08_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT08_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT08_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT08_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT08_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT09_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT09_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT09_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT09_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT09_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT09_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT09_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT09_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT10_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT10_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT10_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT10_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT10_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT10_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT10_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT10_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT11_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT11_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT11_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT11_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT11_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT11_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT11_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT11_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT12_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT12_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT12_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT12_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT12_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT12_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT12_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT12_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT13_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT13_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT13_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT13_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT13_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT13_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT13_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT13_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT14_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT14_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT14_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT14_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT14_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT14_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT14_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT14_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT15_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT15_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT15_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT15_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT15_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT15_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT15_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT15_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT16_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT16_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT16_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT16_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT16_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT16_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT16_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT16_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT17_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT17_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT17_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT17_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT17_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT17_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT17_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT17_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT18_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT18_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT18_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT18_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT18_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT18_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT18_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT18_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT19_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT19_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT19_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT19_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT19_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT19_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT19_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT19_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT20_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT20_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT20_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT20_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT20_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT20_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT20_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT20_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT21_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT21_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT21_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT21_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT21_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT21_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT21_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT21_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT22_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT22_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT22_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT22_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT22_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT22_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT22_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT22_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP0_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP1_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP2_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP3_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP4_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP5_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP5_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_TH_GBT23_EGROUP6_CTRL       => register_map_control_s.CR_TH_GBT23_EGROUP6_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [5,6] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP0_CTRL       => register_map_control_s.CR_FH_GBT23_EGROUP0_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP1_CTRL       => register_map_control_s.CR_FH_GBT23_EGROUP1_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP2_CTRL       => register_map_control_s.CR_FH_GBT23_EGROUP2_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP3_CTRL       => register_map_control_s.CR_FH_GBT23_EGROUP3_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_FH_GBT23_EGROUP4_CTRL       => register_map_control_s.CR_FH_GBT23_EGROUP4_CTRL       <= register_write_data_40_s(63 downto 0);   -- See Central Router Doc, indices [3,4] are optimized out in wideMode
  when REG_CR_TH_UPDATE_CTRL              => register_map_control_s.CR_TH_UPDATE_CTRL              <= "1";                                     -- See Central Router Doc
  when REG_CR_FH_UPDATE_CTRL              => register_map_control_s.CR_FH_UPDATE_CTRL              <= "1";                                     -- See Central Router Doc
  when REG_GBT_EMU_ENA                    => register_map_control_s.GBT_EMU_ENA.TOHOST             <= register_write_data_40_s(1 downto 1);    -- Enable GBT dummy emulator ToHost
                                             register_map_control_s.GBT_EMU_ENA.TOFRONTEND         <= register_write_data_40_s(0 downto 0);    -- Enable GBT dummy emulator ToFrontEnd
  when REG_GBT_EMU_CONFIG_WE_ARRAY        => register_map_control_s.GBT_EMU_CONFIG_WE_ARRAY        <= register_write_data_40_s(6 downto 0);    -- write enable array, every bit is one emulator RAM block
  when REG_GBT_EMU_CONFIG                 => register_map_control_s.GBT_EMU_CONFIG.WRADDR          <= register_write_data_40_s(45 downto 32);  -- write address bus
                                             register_map_control_s.GBT_EMU_CONFIG.WRDATA          <= register_write_data_40_s(15 downto 0);   -- write data bus
  when REG_GBT_LOGIC_RESET                => register_map_control_s.GBT_LOGIC_RESET                <= register_write_data_40_s(63 downto 0);   -- Not internally connected (?)
  when REG_GBT_GENERAL_CTRL               => register_map_control_s.GBT_GENERAL_CTRL               <= register_write_data_40_s(0 downto 0);    -- Alignment chk reset (not self clearing)
  when REG_GBT_MODE_CTRL                  => register_map_control_s.GBT_MODE_CTRL.DESMUX_USE_SW    <= register_write_data_40_s(2 downto 2);    -- DESMUX_USE_SW
                                             register_map_control_s.GBT_MODE_CTRL.RX_ALIGN_SW      <= register_write_data_40_s(1 downto 1);    -- RX_ALIGN_SW
                                             register_map_control_s.GBT_MODE_CTRL.RX_ALIGN_TB_SW   <= register_write_data_40_s(0 downto 0);    -- RX_ALIGN_TB_SW
  when REG_GBT_RXSLIDE                    => register_map_control_s.GBT_RXSLIDE.BF1                <= register_write_data_40_s(59 downto 48);  -- RxSlide select [23:12]
                                             register_map_control_s.GBT_RXSLIDE.BF2                <= register_write_data_40_s(43 downto 32);  -- RxSlide select [11:0]
                                             register_map_control_s.GBT_RXSLIDE.BF3                <= register_write_data_40_s(27 downto 16);  -- RxSlide manual [23:12
                                             register_map_control_s.GBT_RXSLIDE.BF4                <= register_write_data_40_s(11 downto 0);   -- RxSlide manual [11:0]
  when REG_GBT_TXUSRRDY                   => register_map_control_s.GBT_TXUSRRDY.BF1               <= register_write_data_40_s(27 downto 16);  -- TxUsrRdy [23:12]
                                             register_map_control_s.GBT_TXUSRRDY.BF2               <= register_write_data_40_s(11 downto 0);   -- TxUsrRdy [11:0]
  when REG_GBT_RXUSRRDY                   => register_map_control_s.GBT_RXUSRRDY.BF1               <= register_write_data_40_s(27 downto 16);  -- RxUsrRdy [23:12]
                                             register_map_control_s.GBT_RXUSRRDY.BF2               <= register_write_data_40_s(11 downto 0);   -- RxUsrRdy [11:0]
  when REG_GBT_GTTX_RESET                 => register_map_control_s.GBT_GTTX_RESET.BF1             <= register_write_data_40_s(30 downto 28);  -- SOFT_RESET [5:3]
                                             register_map_control_s.GBT_GTTX_RESET.BF2             <= register_write_data_40_s(27 downto 16);  -- GTTX_RESET [23:12]
                                             register_map_control_s.GBT_GTTX_RESET.BF3             <= register_write_data_40_s(14 downto 12);  -- SOFT_RESET [2:0]
                                             register_map_control_s.GBT_GTTX_RESET.BF4             <= register_write_data_40_s(11 downto 0);   -- GTTX_RESET [11:0]
  when REG_GBT_GTRX_RESET                 => register_map_control_s.GBT_GTRX_RESET.BF1             <= register_write_data_40_s(27 downto 16);  -- GTRX_RESET [23:0]
                                             register_map_control_s.GBT_GTRX_RESET.BF2             <= register_write_data_40_s(11 downto 0);   -- GTRX_RESET [11:0]
  when REG_GBT_PLL_RESET                  => register_map_control_s.GBT_PLL_RESET.BF1              <= register_write_data_40_s(30 downto 28);  -- QPLL_RESET [5:3]
                                             register_map_control_s.GBT_PLL_RESET.BF2              <= register_write_data_40_s(27 downto 16);  -- CPLL_RESET [23:12]
                                             register_map_control_s.GBT_PLL_RESET.BF3              <= register_write_data_40_s(14 downto 12);  -- QPLL_RESET [2:0]
                                             register_map_control_s.GBT_PLL_RESET.BF4              <= register_write_data_40_s(11 downto 0);   -- CPLL_RESET [11:0]
  when REG_GBT_SOFT_TX_RESET              => register_map_control_s.GBT_SOFT_TX_RESET.BF1          <= register_write_data_40_s(30 downto 28);  -- SOFT_TX_RESET_ALL [5:3]
                                             register_map_control_s.GBT_SOFT_TX_RESET.BF2          <= register_write_data_40_s(27 downto 16);  -- SOFT_TX_RESET_GT [23:12]
                                             register_map_control_s.GBT_SOFT_TX_RESET.BF3          <= register_write_data_40_s(14 downto 12);  -- SOFT_TX_RESET_ALL [2:0]
                                             register_map_control_s.GBT_SOFT_TX_RESET.BF4          <= register_write_data_40_s(11 downto 0);   -- SOFT_TX_RESET_GT [11:0]
  when REG_GBT_SOFT_RX_RESET              => register_map_control_s.GBT_SOFT_RX_RESET.BF1          <= register_write_data_40_s(30 downto 28);  -- SOFT_RX_RESET_ALL [5:3]
                                             register_map_control_s.GBT_SOFT_RX_RESET.BF2          <= register_write_data_40_s(27 downto 16);  -- SOFT_RX_RESET_GT [23:12]
                                             register_map_control_s.GBT_SOFT_RX_RESET.BF3          <= register_write_data_40_s(14 downto 12);  -- SOFT_RX_RESET_ALL [2:0]
                                             register_map_control_s.GBT_SOFT_RX_RESET.BF4          <= register_write_data_40_s(11 downto 0);   -- SOFT_RX_RESET_GT [11:0]
  when REG_GBT_ODD_EVEN                   => register_map_control_s.GBT_ODD_EVEN.BF1               <= register_write_data_40_s(27 downto 16);  -- OddEven [23:12]
                                             register_map_control_s.GBT_ODD_EVEN.BF2               <= register_write_data_40_s(11 downto 0);   -- OddEven [11:0]
  when REG_GBT_TOPBOT                     => register_map_control_s.GBT_TOPBOT.BF1                 <= register_write_data_40_s(27 downto 16);  -- TopBot [23:12]
                                             register_map_control_s.GBT_TOPBOT.BF2                 <= register_write_data_40_s(11 downto 0);   -- TopBot [11:0]
  when REG_GBT_TX_TC_DLY_VALUE1           => register_map_control_s.GBT_TX_TC_DLY_VALUE1           <= register_write_data_40_s(47 downto 0);   -- TX_TC_DLY_VALUE [47:0]
  when REG_GBT_TX_TC_DLY_VALUE2           => register_map_control_s.GBT_TX_TC_DLY_VALUE2           <= register_write_data_40_s(47 downto 0);   -- TX_TC_DLY_VALUE [95:48]
  when REG_GBT_TX_OPT                     => register_map_control_s.GBT_TX_OPT                     <= register_write_data_40_s(47 downto 0);   -- TX_OPT
  when REG_GBT_RX_OPT                     => register_map_control_s.GBT_RX_OPT                     <= register_write_data_40_s(47 downto 0);   -- RX_OPT
  when REG_GBT_DATA_TXFORMAT              => register_map_control_s.GBT_DATA_TXFORMAT.BF1          <= register_write_data_40_s(55 downto 32);  -- DATA_TXFORMAT [47:24]
                                             register_map_control_s.GBT_DATA_TXFORMAT.BF2          <= register_write_data_40_s(23 downto 0);   -- DATA_TXFORMAT [23:0]
  when REG_GBT_DATA_RXFORMAT              => register_map_control_s.GBT_DATA_RXFORMAT.BF1          <= register_write_data_40_s(55 downto 32);  -- DATA_RXFORMAT [47:24]
                                             register_map_control_s.GBT_DATA_RXFORMAT.BF2          <= register_write_data_40_s(23 downto 0);   -- DATA_RXFORMAT [23:0]
  when REG_GBT_TX_RESET                   => register_map_control_s.GBT_TX_RESET.BF1               <= register_write_data_40_s(27 downto 16);  -- TX Logic reset [23:12]
                                             register_map_control_s.GBT_TX_RESET.BF2               <= register_write_data_40_s(11 downto 0);   -- TX Logic reset [11:0]
  when REG_GBT_RX_RESET                   => register_map_control_s.GBT_RX_RESET.BF1               <= register_write_data_40_s(27 downto 16);  -- RX Logic reset [23:12]
                                             register_map_control_s.GBT_RX_RESET.BF2               <= register_write_data_40_s(11 downto 0);   -- RX Logic reset [11:0]
  when REG_GBT_TX_TC_METHOD               => register_map_control_s.GBT_TX_TC_METHOD.BF1           <= register_write_data_40_s(27 downto 16);  -- TX time domain crossing method [23:12]
                                             register_map_control_s.GBT_TX_TC_METHOD.BF2           <= register_write_data_40_s(11 downto 0);   -- TX time domain crossing method [11:0]
  when REG_GBT_OUTMUX_SEL                 => register_map_control_s.GBT_OUTMUX_SEL.BF1             <= register_write_data_40_s(27 downto 16);  -- Descrambler output MUX selection [23:12]
                                             register_map_control_s.GBT_OUTMUX_SEL.BF2             <= register_write_data_40_s(11 downto 0);   -- Descrambler output MUX selection [11:0]
  when REG_GBT_DNLNK_FO_SEL               => register_map_control_s.GBT_DNLNK_FO_SEL               <= register_write_data_40_s(31 downto 0);   -- ToHost FanOut/Selector. Every bitfield is a channel:
                                                                                                                                               --   1 : GBT_EMU, select GBT Emulator for a specific CentralRouter channel
                                                                                                                                               --   0 : GBT_WRAP, select real GBT link for a specific CentralRouter channel
                                                                                                                                               
  when REG_GBT_UPLNK_FO_SEL               => register_map_control_s.GBT_UPLNK_FO_SEL               <= register_write_data_40_s(31 downto 0);   -- ToFrontEnd FanOut/Selector. Every bitfield is a channel:
                                                                                                                                               --   1 : GBT_EMU, select GBT Emulator for a specific GBT link
                                                                                                                                               --   0 : TTC_DEC, select CentralRouter data (including TTC) for a specific GBT link
                                                                                                                                               
  when REG_HK_CTRL_CDCE                   => register_map_control_s.HK_CTRL_CDCE.REF_SEL           <= register_write_data_40_s(2 downto 2);    -- REF_SEL
                                             register_map_control_s.HK_CTRL_CDCE.PD                <= register_write_data_40_s(1 downto 1);    -- PD
                                             register_map_control_s.HK_CTRL_CDCE.SYNC              <= register_write_data_40_s(0 downto 0);    -- SYNC
  when REG_HK_CTRL                        => register_map_control_s.HK_CTRL.I2C_CONFIG_TRIG        <= register_write_data_40_s(1 downto 1);    -- i2c_config_trig
                                             register_map_control_s.HK_CTRL.I2C_CLKFREQ_SEL        <= register_write_data_40_s(0 downto 0);    -- i2c_clkfreq_sel
  when REG_SPI_WR                         => register_map_control_s.SPI_WR.SPI_DIN                 <= register_write_data_40_s(31 downto 0);   -- SPI WRITE Data
                                             register_map_control_s.SPI_WR.SPI_WREN                <= not register_map_monitor_s.register_map_hk_monitor.SPI_WR_SPI_FULL; -- Any write to this register triggers an SPI Write
  when REG_SPI_RD                         => register_map_control_s.SPI_RD.SPI_RDEN                <= "1";                                     -- Any write to this register pops the last SPI data from the FIFO
  when REG_I2C_WR                         => register_map_control_s.I2C_WR.BF2                     <= register_write_data_40_s(24 downto 24);  -- Write two bytes
                                             register_map_control_s.I2C_WR.BF3                     <= register_write_data_40_s(23 downto 16);  -- Data byte 2
                                             register_map_control_s.I2C_WR.BF4                     <= register_write_data_40_s(15 downto 8);   -- Data byte 1
                                             register_map_control_s.I2C_WR.BF5                     <= register_write_data_40_s(7 downto 1);    -- Slave address
                                             register_map_control_s.I2C_WR.BF6                     <= register_write_data_40_s(0 downto 0);    -- READ/<o>WRITE</o>
                                             register_map_control_s.I2C_WR.I2C_WREN                <= not register_map_monitor_s.register_map_hk_monitor.I2C_WR_I2C_FULL; -- Any write to this register triggers an I2C read or write sequence
  when REG_I2C_RD                         => register_map_control_s.I2C_RD.I2C_RDEN                <= "1";                                     -- Any write to this register pops the last I2C data from the FIFO
  when REG_DEBUG_PORT_CLK                 => register_map_control_s.DEBUG_PORT_CLK                 <= register_write_data_40_s(3 downto 0);    -- Debug clock and L1A port on SMA HTGx#4
  when REG_DEBUG_PORT_GBT                 => register_map_control_s.DEBUG_PORT_GBT                 <= register_write_data_40_s(6 downto 0);    -- Debug GBT data bit N (119..0) on SMA HTGx#3
  when REG_INT_TEST_2                     => register_map_control_s.INT_TEST_2                     <= "1";                                     -- Fire a test MSIx interrupt #2
  when REG_INT_TEST_3                     => register_map_control_s.INT_TEST_3                     <= "1";                                     -- Fire a test MSIx interrupt #3
